/*
 * Copyright (c) 2015 NEC Corporation. All rights reserved.
 *
 * This program and the accompanying materials are made available under the
 * terms of the Eclipse Public License v1.0 which accompanies this distribution,
 * and is available at http://www.eclipse.org/legal/epl-v10.html
 */

package org.opendaylight.vtn.manager.neutron.impl;

import static org.mockito.Mockito.any;
import static org.mockito.Mockito.anyBoolean;
import static org.mockito.Mockito.anyLong;
import static org.mockito.Mockito.mock;
import static org.mockito.Mockito.when;

import java.util.Set;
import java.util.concurrent.Future;
import java.util.concurrent.TimeUnit;
import java.util.concurrent.TimeoutException;

import com.google.common.base.Optional;
import com.google.common.util.concurrent.CheckedFuture;
import com.google.common.util.concurrent.Futures;

import org.junit.Assert;

import org.opendaylight.controller.md.sal.common.api.data.ReadFailedException;

import org.opendaylight.yangtools.yang.binding.DataObject;
import org.opendaylight.yangtools.yang.common.RpcError.ErrorType;
import org.opendaylight.yangtools.yang.common.RpcError;
import org.opendaylight.yangtools.yang.common.RpcResult;
import org.opendaylight.yangtools.yang.common.RpcResultBuilder;

/**
 * Abstract base class for JUnit tests.
 */
public abstract class TestBase extends Assert {

    /**
     * An array of UUIDs generated by Neutron.
     */
    protected static final String[] NEUTRON_UUID_ARRAY = {
        "C387EB44-7832-49F4-B9F0-D30D27770883",
        "4790F3C1-AB34-4ABC-B7A5-C1B5C7202389",
        "52B1482F-A41E-409F-AC68-B04ACFD07779",
        "6F3FCFCF-C000-4879-84C5-19157CBD1F6A",
        "0D2206F8-B700-4F78-913D-9CE7A2D78473"};

    /**
     * An array of tenat IDs generated by Keystone.
     */
    protected static final String[] TENANT_ID_ARRAY = {
        "E6E005D3-A245-42FC-B038-97730A5150E2",
        "B37B5045-6AE8-48DF-8F98-1058FDD3A63D",
        "3655F990-CC53-48F2-A668-F77896D9D017",
        "E20F7C45-1114-4D9B-AEB8-44A4964B60DA",
        "5FB6A2BB-7771-4CE6-BF33-282283245705"};

    /**
     * Ensure that the given two objects are identical.
     *
     * @param set  A set of tested objects.
     * @param o1   An object to be tested.
     * @param o2   An object to be tested.
     */
    protected static void testEquals(Set<Object> set, Object o1, Object o2) {
        assertEquals(o1, o2);
        assertEquals(o2, o1);
        assertEquals(o1, o1);
        assertEquals(o2, o2);
        assertEquals(o1.hashCode(), o2.hashCode());
        assertFalse(o1.equals(null));
        assertFalse(o1.equals(new Object()));
        assertFalse(o1.equals("string"));
        assertFalse(o1.equals(set));

        for (Object o : set) {
            assertFalse("o1=" + o1 + ", o=" + o, o1.equals(o));
            assertFalse(o.equals(o1));
        }

        assertTrue(set.add(o1));
        assertFalse(set.add(o1));
        assertFalse(set.add(o2));
    }

    /**
     * Create a response of read request on a MD-SAL transaction.
     *
     * @param obj  An object to be read.
     *             {@code null} implies the target data is not present.
     * @return  A {@link CheckedFuture} instance.
     * @param <T>  The type of the data object.
     */
    protected static <T extends DataObject> CheckedFuture<Optional<T>, ReadFailedException> getReadResult(
        T obj) {
        Optional<T> opt = Optional.fromNullable(obj);
        return Futures.immediateCheckedFuture(opt);
    }

    /**
     * Create an error response of read request on a MD-SAL transaction.
     *
     * @param type   A class which indicates the type of the return value.
     * @param cause  A throwable which indicates the cause of error.
     * @return  A {@link CheckedFuture} instance.
     * @param <T>  The type of the return value.
     */
    protected static <T extends DataObject> CheckedFuture<Optional<T>, ReadFailedException> getReadFailure(
        Class<T> type, Throwable cause) {
        String msg = "DS read failed";
        RpcError err = RpcResultBuilder.newError(
            ErrorType.APPLICATION, "failed", msg, null, null, cause);
        ReadFailedException rfe = new ReadFailedException(msg, cause, err);
        return Futures.immediateFailedCheckedFuture(rfe);
    }

    /**
     * Create a timeout error response of read request on a MD-SAL transaction.
     *
     * @param type  A class which indicates the type of the return value.
     * @return  A {@link CheckedFuture} instance.
     * @param <T>  The type of the return value.
     * @throws Exception  An error occurred.
     */
    protected static <T extends DataObject> CheckedFuture<Optional<T>, ReadFailedException> getReadTimeoutFailure(
        Class<T> type) throws Exception {
        CheckedFuture<Optional<T>, ReadFailedException> future =
            mock(CheckedFuture.class);

        when(future.cancel(anyBoolean())).thenReturn(false);
        when(future.isCancelled()).thenReturn(false);
        when(future.isDone()).thenReturn(false);

        when(future.get()).thenThrow(
            new AssertionError("get() should never be called."));
        when(future.checkedGet()).thenThrow(
            new AssertionError("checkedGet() should never be called."));
        when(future.get(anyLong(), any(TimeUnit.class))).
            thenThrow(new TimeoutException("DS read timed out"));
        when(future.checkedGet(anyLong(), any(TimeUnit.class))).
            thenThrow(new TimeoutException("DS read timed out"));

        return future;
    }

    /**
     * Return a future that contains RPC result that indicates successful
     * completion.
     *
     * @param output  The output of the RPC.
     * @param <O>     The type of the RPC output.
     * @return  A future that contains the RPC result.
     */
    protected static <O> Future<RpcResult<O>> getRpcFuture(O output) {
        RpcResult<O> result = RpcResultBuilder.success(output).build();
        return Futures.immediateFuture(result);
    }
}
