/*
 * Copyright (c) 2011-2013 NEC Corporation
 * All rights reserved.
 * 
 * This program and the accompanying materials are made available under the
 * terms of the Eclipse Public License v1.0 which accompanies this
 * distribution, and is available at http://www.eclipse.org/legal/epl-v10.html
 */

#ifndef	_PFC_IPC_PFCD_H
#define	_PFC_IPC_PFCD_H

/*
 * Define IPC services provided by the PFC daemon.
 */

#include <pfc/ipc.h>
#include <pfc/modconst.h>

/*
 * Name of IPC channel associated with the PFC daemon.
 */
#define	PFCD_IPC_CHANNEL	"pfcd"

/*
 * Name of IPC services provided by the PFC daemon.
 */
#define	PFCD_IPC_SERVICE	PFC_MODULE_CORE_PREFIX PFCD_IPC_CHANNEL

/*
 * IPC event types generated by the PFC daemon.
 */

/*
 * PFCD_IPCEVENT_SYS_STOP - Notify system shutdown.
 *
 * The PFC daemon sends this IPC event when it enters the system shutdown
 * sequence.
 *
 * This event contains one UINT8 additional data.
 *   - 1 is set if the shutdown is triggered by normal shutdown.
 *   - zero is set if the shutdown is triggered by an error.
 */
#define	PFCD_IPCEVENT_SYS_STOP		PFC_CONST_U(0)

#endif	/* !_PFC_IPC_PFCD_H */
