#
# Copyright (c) 2014 NEC Corporation
# All rights reserved.
#
# This program and the accompanying materials are made available under the
# terms of the Eclipse Public License v1.0 which accompanies this
# distribution, and is available at http://www.eclipse.org/legal/epl-v10.html
#

##
## Makefile that drives the production of unclib module.
##

include ../defs.mk

CXX_SOURCES = \
	lib_unc.cc \
	unclib_module.cc

include ../rules.mk
