/*
 * Copyright (c) 2013-2014 NEC Corporation
 * All rights reserved.
 *
 * This program and the accompanying materials are made available under the
 * terms of the Eclipse Public License v1.0 which accompanies this
 * distribution, and is available at http://www.eclipse.org/legal/epl-v10.html
 */

package org.opendaylight.vtn.manager.neutron;

import org.junit.Assert;

/**
 * Abstract base class for JUnit tests.
 */
public abstract class TestBase extends Assert {
  /**
   * String Declaration for OpenFlow.
   */
  protected static final String OPENFLOW = "OF";

  /**
   * String Declaration for Production.
   */
  protected static final String PRODUCTION = "PR";

  /**
   * String Declaration for Onepk.
   */
  protected static final String ONEPK = "PK";

  /**
   * String Declaration for Pcep.
   */
  protected static final String PCEP = "PE";

  /**
   * String Declaration for Bridge Name.
   */
  protected static final String BRIDGENAME="br-int";

  /**
   * String Declaration for Fail Mode.
   */
  protected static final String FAILMODE="secure";

  /**
   * String Declaration for Protcols.
   */
  protected static final String PROTOCOLS="OpenFlow10";

  /**
   * String Declaration for Port Name.
   */
  protected static final String PORTNAME="ens33";

  /**
   * An array of UUIDs generated by Neutron.
   */
  protected static final String[] NEUTRON_UUID_ARRAY
    = {"C387EB44-7832-49F4-B9F0-D30D27770883",
      "4790F3C1-AB34-4ABC-B7A5-C1B5C7202389",
      "52B1482F-A41E-409F-AC68-B04ACFD07779",
      "6F3FCFCF-C000-4879-84C5-19157CBD1F6A",
      "0D2206F8-B700-4F78-913D-9CE7A2D78473"};

  /**
   * An array of tenat IDs generated by Keystone.
   */
  protected static final String[] TENANT_ID_ARRAY
    = {"E6E005D3A24542FCB03897730A5150E2",
      "B37B50456AE848DF8F981058FDD3A63D",
      "3655F990CC5348F2A668F77896D9D017",
      "E20F7C4511144D9BAEB844A4964B60DA",
      "5FB6A2BB77714CE6BF33282283245705"};

  /**
   * An array of MAC Addresses.
   */
  protected static final String[] MAC_ADDR_ARRAY
    = {"EA:75:F6:3A:30:50",
      "20:C1:F2:C0:A5:BF",
      "33:C2:B0:C3:B4:40",
      "9B:D9:F0:C4:31:B1",
      "70:A8:A6:C2:FA:D2"};
  /**
   * An array of elements to update row.
  */
  protected static final String[][] RW_UPDT_INP_ARY = {
    // Inputs to the function - Interface , UUID , and non null value , non-null value
    {"PE", "bridge", "br-int", "Interface",
      "9b2b6560-f21e-11e3-a6a2-0002a5d5c51b", "not_null",
      "not_null", "1", "1", "ex_msg", "0", "0"},

    // When Neutron Port as Bridge
    {"PE", "bridge-int", "br-int", "Interface",
      "9b2b6560-f21e-11e3-a6a2-0002a5d5c51b", "not_null",
      "null", "0", "1", "null_msg", "0", "0" },

    // when Neutron port new row is NUll
    {"PE", "bridge-int", "br-int", "Interface",
      "9b2b6560-f21e-11e3-a6a2-0002a5d5c51b", "null", "null",
      "0", "0", "null_msg", "0", "1" },

    // Neutron Port is Null.
    {"PE", "bridge-int", "br-int", "Interface",
      "9b2b6560-f21e-11e3-a6a2-0002a5d5c51b", "not_null",
      "not_null", "0", "0", "ex_msg", "0", "1" },

    //when there is no external id
    {"PE", "intf", "interface1", "Interface",
      "9b2b6560-f21e-11e3-a6a2-0002a5d5c51b", "not_null",
      "not_null", "0", "0", "no_ex_msg", "0", "1",
      "1iface-id", "C387EB44-7832-49F4-B9F0-D30D27770883"},

    // when external id is wrong
    {"PE", "intf", "interface1", "Interface",
      "9b2b6560-f21e-11e3-a6a2-0002a5d5c51b", "not_null",
      "not_null", "1", "0", "null_msg", "0", "0",
      "iface-id", "C387EB44-7832-49F4-B9F0-D30D27770883" },

    {"PE", "intf-neutron", "interface1", "Interface",
      "9b2b6560-f21e-11e3-a6a2-0002a5d5c51b", "not_null",
      "not_null", "0", "0", "no_ex_msg", "1", "0",
      "iface-id", "C387EB44-7832-49F4-B9F0-D30D27770883" },

    {"PE", "intf-neutron", "interface1", "Interface",
      "9b2b6560-f21e-11e3-a6a2-0002a5d5c51b", "not_null",
      "not_null", "0", "0", "no_ex_msg", "1", "0",
      "iface-id", "C387EB44-7832-49F4-B9F0-D30D27770883" }};

  /**
   * Exception message to be checked.
   */
  protected static final String EXCEPTION_MSG =
    "org.opendaylight.ovsdb.lib.table.Bridge cannot be cast to org.opendaylight.ovsdb.lib.table.Interface";

  /**
   * An array of elements to update row with type OF.
   */
  protected static final String[][] RW_UPDT_INP_OF_ARY
    ={{"Set_OF_neutron", "0", "interface1", "iface-id",
      "C387EB44-7832-49F4-B9F0-D30D27770883", "Interface",
      "9b2b6560-f21e-11e3-a6a2-0002a5d5c51b",
      "0", "0", "no_ex_msg", "1", "0" },

      {"Set_OF_neutron", "12344321", "interface1", "iface-id",
        "C387EB44-7832-49F4-B9F0-D30D27770883", "Interface",
        "9b2b6560-f21e-11e3-a6a2-0002a5d5c51b",
        "0", "0", "no_ex_msg", "1", "0" },

      {"Set_OF_neutron", "12345678", "interface1", "iface-id",
        "C387EB44-7832-49F4-B9F0-D30D27770883", "Interface",
        "9b2b6560-f21e-11e3-a6a2-0002a5d5c51b",
        "0", "0", "no_ex_msg", "1", "0" },

      {"Set_OF_neutron", "12345678", "interface1", "iface-id",
        "C387EB44-7832-49F4-B9F0-D30D27770883", "Interface",
        "", "0", "0", "no_ex_msg", "1", "0" }  ,

      {"Set_OF_neutron", "23456789", "interface1", "iface-id",
        "C387EB44-7832-49F4-B9F0-D30D27770883", "Interface",
        "85c27f20-f218-11e3-a7b6-0002a5d5c51b",
        "0", "0", "no_ex_msg", "1", "0" },

      {"Set_OF_neutron", "98765432", "interface1", "iface-id",
        "C387EB44-7832-49F4-B9F0-D30D27770883", "Interface",
        "85c27f20-f218-11e3-a7b6-0002a5d5c51b",
        "0", "0", "no_ex_msg", "1", "0" },

      {"Set_OF_Null", "12345678", "interface1", "iface-id",
        "C387EB44-7832-49F4-B9F0-D30D27770883", "Interface",
        "0d0ff2a0-f219-11e3-a482-0002a5d5c51b",
        "1", "0", "null_msg", "0", "0" },

      {"Set_OF_Bridge", "98765432", "interface1", "iface-id",
        "C387EB44-7832-49F4-B9F0-D30D27770883", "Interface",
        "85c27f20-f218-11e3-a7b6-0002a5d5c51b",
        "1", "0", "ex_msg", "0", "0" },

      {"Set_OF_Bridge_intf", "98765432", "interface1", "iface-id",
        "C387EB44-7832-49F4-B9F0-D30D27770883", "Interface",
        "85c27f20-f218-11e3-a7b6-0002a5d5c51b",
        "1", "0", "ex_msg", "0", "0" },

      {"Set_OF_neutron", "12345678", "interface1", "iface-id",
        "C387EB44-7832-49F4-B9F0-D30D27770883", "Interface",
        "85c27f20-f218-11e3-a7b6-0002a5d5c51b",
        "0", "0", "no_ex_msg", "1", "0" } };

  /**
   * An array of elements to create network.
   */
  protected static final String[][] CREATE_NETWORK_ARRAY =  {
    {"OF", "66767646" , "yes", "1", "null" },
    {"OF", "66767645" , "yes", "0", "" },
    {"PK", "0xDEADBEEFCAFE0001L" , "yes", "1", "null" },
    {"PR", "0xDEADBEEFCAFE0001L", "yes", "0", "" },
    {"PE", "", "yes", "0", "" }
  };

  /**
   * An array of elements to remove row.
   */
  protected static final String[][] ROW_REMOVE_ARRAY =  {
    {"66767644", "interface1", "0D2206F8-B700-4F78-913D-9CE7A2D78473", "set_manager", "0"},
    {"66767644", "interface1", "C387EB44-7832-49F4-B9F0-D30D27770883", "set_manager", "0"},
    {"12345678", "interface1", "C387EB44-7832-49F4-B9F0-D30D27770883", "set_manager", "0"},
    {"66767644", null, "0D2206F8-B700-4F78-913D-9CE7A2D78473", "set_manager", "0"},
    {"66767644", "interface1", "0D2206F8-B700-4F78-913D-9CE7A2D78473", "unset_manager", "1"},
  };

  /**
   * An array of elements to update row.
   */
  protected static final String[][] ROW_UPDATE_PORT_ARRAY = {
    {"OF", "56456644", "interface1", "C387EB44-7832-49F4-B9F0-D30D27770883", "set_port", "", "0" },
    {"OF", "56456644", "interface1", "C387EB44-7832-49F4-B9F0-D30D27770883", "set_null_port", "", "0" },
    {"OF", "56456644", "interface1", "C387EB44-7832-49F4-B9F0-D30D27770883", "set_empty_port", "", "0" },
    {"OF", "12345678", "interface1", "C387EB44-7832-49F4-B9F0-D30D27770883", "without_port", "65534", "0" },
    {"OF", "56456644", "interface1", "4790F3C1-AB34-4ABC-B7A5-C1B5C7202389", "", "65534", "0" },
    {"OF", "56456644", "interface1", "52B1482F-A41E-409F-AC68-B04ACFD07779", "", "65534", "0" },
    {"OF", "56456644", "interface1", "8c781fc0-f215-11e3-aac3-0002a5d5c51b", "", "65534", "0" },
    {"OF", "56456644", "interface1", "0D2206F8-B700-4F78-913D-9CE7A2D78473", "", "65534", "0" },
    };
}
