/*
 * Copyright (c) 2012-2014 NEC Corporation
 * All rights reserved.
 *
 * This program and the accompanying materials are made available under the
 * terms of the Eclipse Public License v1.0 which accompanies this
 * distribution, and is available at http://www.eclipse.org/legal/epl-v10.html
 */

#ifndef UNC_UPLL_SVC_H_
#define UNC_UPLL_SVC_H_

#include "base.h"

UNC_C_BEGIN_DECL

#define UPLL_IPC_CHANNEL_NAME "lgcnwd"  /* UPLL IPC Channel Name */
#define UPLL_IPC_SERVICE_NAME "upll"    /* UPLL IPC Service Name */

/* UPLL IPC Service Ids */
typedef enum {
  UPLL_EDIT_SVC_ID = 0,               /* Key Tree edit services */
  UPLL_READ_SVC_ID = 1,               /* Key Tree read services */
  UPLL_CONTROL_SVC_ID = 2,            /* Key Tree control services */
  UPLL_GLOBAL_CONFIG_SVC_ID = 3       /* UPLL GlobalConfig services */
} upll_service_ids_t;

/* UPLL IPC Operations supported under GlobalConfig Service ID */
typedef enum {
  UPLL_IS_CANDIDATE_DIRTY_OP = 101,
  UPLL_IMPORT_CTRLR_CONFIG_OP = 102,
  UPLL_MERGE_IMPORT_CONFIG_OP = 103,
  UPLL_CLEAR_IMPORT_CONFIG_OP = 104,
  UPLL_IS_KEY_TYPE_IN_USE_OP = 105,
  UPLL_UPPL_UPDATE_OP = 106,
  UPLL_CFG_BATCH_START_OP = 107,
  UPLL_CFG_BATCH_ALIVE_OP = 108,
  UPLL_CFG_BATCH_END_OP = 109,
} upll_global_config_op_t;

/* Event Types generated by UPLL */
typedef enum {
  UPLL_EV_CONFIG_NOTIFICATION = 0,
  UPLL_EV_OPER_NOTIFICATION = 1
} upll_event_type_t;

UNC_C_END_DECL

#endif  /* UNC_UPLL_SVC_H_ */
