# Copyright (c) 2016 NEC Corporation
# All rights reserved.
#
# This program and the accompanying materials are made available under the
# terms of the Eclipse Public License v1.0 which accompanies this
# distribution, and is available at http://www.eclipse.org/legal/epl-v10.html

[GET_BASEURL]
type=url_string
value="/restconf/operations"

[SLASH]
type=url_string
value="/"

[VTN]
type=url_string
value="vtn-flow"

[DATAFLOW]
type=url_string
value="get-data-flow"

[COLON]
type=url_string
value=":"

[DATAFLOW_GETSUPPORT_URL]
type=url_string
url_format=GET_BASEURL,SLASH,VTN,COLON,DATAFLOW

[READ]
url=DATAFLOW_GETSUPPORT_URL

[valid]
type=bool
key=""
mandatory=no
build_support=no
parse_support=no
struct_name=data_flow

[tenant_name]
type=string
key="tenant-name"
is_child=yes
struct_name=virt_node_path
check_bool_set=yes
build_support=no
mandatory=no
parse_support=yes

[bridge_name]
type=string
key="bridge-name"
is_child=yes
struct_name=virt_node_path
check_bool_set=yes
build_support=no
mandatory=no
parse_support=yes

[terminal_name]
type=string
key="terminal-name"
is_child=yes
struct_name=virt_node_path
check_bool_set=yes
build_support=no
mandatory=no
parse_support=yes

[if_name]
type=string
key="interface-name"
is_child=yes
struct_name=virt_node_path
check_bool_set=yes
build_support=no
mandatory=yes
parse_support=yes

[reason]
type=string
key="reason"
is_child=yes
struct_name=virtual_route
check_bool_set=yes
build_support=no
mandatory=yes
parse_support=yes

[virt_order]
type=int
key="order"
is_child=yes
struct_name=virtual_route
check_bool_set=yes
build_support=no
mandatory=yes
parse_support=yes

[virt_node_path]
type=struct
key="virtual-node-path"
is_child=yes
struct_name=virtual_route
members=tenant_name,bridge_name,terminal_name,if_name,valid
check_bool_set=yes
build_support=no
mandatory=yes
parse_support=yes

[virtual_route]
type=array
key="virtual-route"
is_child=yes
struct_name=virtual_route
members=virt_order,reason,virt_node_path,valid
check_bool_set=yes
build_support=no
mandatory=yes
parse_support=yes

[act_vlan_id]
type=int
key="vlan-id"
is_child=yes
struct_name=vlan_id
check_bool_set=yes
build_support=no
mandatory=no
parse_support=yes

[vlan_id]
type=array
key="vtn-set-vlan-id-action"
is_child=yes
struct_name=vlan_id
members=act_vlan_id,valid
check_bool_set=no
build_support=no
mandatory=no
parse_support=yes

[pop_vlan]
type=int
key="vtn-pop-vlan-action"
is_child=yes
struct_name=da_actions
check_bool_set=no
build_support=no
mandatory=no
parse_support=yes

[da_actions]
type=array
key="actions"
is_child=yes
struct_name=da_actions
members=pop_vlan,vlan_id,valid
check_bool_set=yes
build_support=no
mandatory=no
parse_support=yes

[port_name_ing]
type=string
key="port-name"
is_child=yes
struct_name=phy_ingr_port
check_bool_set=yes
build_support=no
mandatory=yes
parse_support=yes

[port_id_ing]
type=string
key="port-id"
is_child=yes
struct_name=phy_ingr_port
check_bool_set=yes
build_support=no
mandatory=yes
parse_support=yes

[port_name_eg]
type=string
key="port-name"
is_child=yes
struct_name=phy_egr_port
check_bool_set=yes
build_support=no
mandatory=yes
parse_support=yes

[port_id_eg]
type=string
key="port-id"
is_child=yes
struct_name=phy_egr_port
check_bool_set=yes
build_support=no
mandatory=yes
parse_support=yes

[node]
type=string
key="node"
is_child=yes
struct_name=physical_route
check_bool_set=yes
build_support=no
mandatory=yes
parse_support=yes

[order]
type=int
key="order"
is_child=yes
struct_name=physical_route
check_bool_set=yes
build_support=no
mandatory=yes
parse_support=yes

[phy_ingr_port]
type=struct
key="physical-ingress-port"
is_child=yes
struct_name=physical_route
members=port_id_ing,port_name_ing,valid
check_bool_set=yes
build_support=no
mandatory=yes
parse_support=yes

[phy_egr_port]
type=struct
key="physical-egress-port"
is_child=yes
struct_name=physical_route
members=port_id_eg,port_name_eg,valid
check_bool_set=yes
build_support=no
mandatory=yes
parse_support=yes

[physical_route]
type=array
key="physical-route"
is_child=yes
struct_name=physical_route
members=node,order,phy_egr_port,phy_ingr_port,valid
check_bool_set=yes
build_support=no
mandatory=yes
parse_support=yes

[flow_id]
type=int
key="flow-id"
is_child=yes
struct_name=data_flow
build_support=no
mandatory=yes
parse_support=yes

[hard_timeout]
type=int
key="hard-timeout"
is_child=yes
struct_name=data_flow
build_support=no
mandatory=yes
parse_support=yes

[idle_timeout]
type=int
key="idle-timeout"
is_child=yes
struct_name=data_flow
build_support=no
mandatory=yes
parse_support=yes

[ig_port_name]
type=string
key="port-name"
is_child=yes
struct_name=data_ingress_port
check_bool_set=yes
build_support=no
mandatory=yes
parse_support=yes

[ig_port_id]
type=string
key="port-id"
is_child=yes
struct_name=data_ingress_port
check_bool_set=yes
build_support=no
mandatory=yes
parse_support=yes

[ig_node]
type=string
key="node"
is_child=yes
struct_name=data_ingress_port
check_bool_set=yes
build_support=no
mandatory=yes
parse_support=yes

[data_ingress_port]
type=struct
key="data-ingress-port"
is_child=yes
struct_name=data_flow
members=ig_node,ig_port_id,ig_port_name,valid
check_bool_set=yes
build_support=no
mandatory=yes
parse_support=yes

[ig_tenant]
type=string
key="tenant-name"
is_child=yes
struct_name=data_ingress_node
check_bool_set=yes
build_support=no
mandatory=no
parse_support=yes

[ig_bridge]
type=string
key="bridge-name"
is_child=yes
struct_name=data_ingress_node
check_bool_set=yes
build_support=no
mandatory=no
parse_support=yes

[ig_term_name]
type=string
key="terminal-name"
is_child=yes
struct_name=data_ingress_node
check_bool_set=yes
build_support=no
mandatory=no
parse_support=yes

[ig_if_name]
type=string
key="interface-name"
is_child=yes
struct_name=data_ingress_node
check_bool_set=yes
build_support=no
mandatory=no
parse_support=yes

[data_ingress_node]
type=struct
key="data-ingress-node"
is_child=yes
struct_name=data_flow
members=ig_bridge,ig_tenant,ig_if_name,ig_term_name,valid
check_bool_set=yes
build_support=no
mandatory=yes
parse_support=yes

[packet_count]
type=int
key="packet-count"
is_child=yes
struct_name=data_flow_stats
check_bool_set=yes
build_support=no
mandatory=yes
parse_support=yes

[second]
type=int
key="second"
is_child=yes
struct_name=duration
check_bool_set=yes
build_support=no
mandatory=yes
parse_support=yes

[nanosecond]
type=int
key="nanosecond"
is_child=yes
struct_name=duration
check_bool_set=yes
build_support=no
mandatory=yes
parse_support=yes

[duration]
type=struct
key="duration"
is_child=no
struct_name=data_flow_stats
members=nanosecond,second,valid
check_bool_set=yes
mandatory=yes
build_support=no
parse_support=yes


[byte_count]
type=int
key="byte-count"
is_child=yes
struct_name=data_flow_stats
check_bool_set=yes
build_support=no
mandatory=yes
parse_support=yes

[data_flow_stats]
type=struct
key="data-flow-stats"
is_child=yes
struct_name=data_flow
members=byte_count,duration,packet_count,valid
check_bool_set=yes
build_support=no
mandatory=yes
parse_support=yes

[vlan]
type=int
key="vlan-id"
is_child=yes
struct_name=da_vtn_ether_match
check_bool_set=yes
build_support=no
mandatory=yes
parse_support=yes

[dst_arr]
type=string
key="destination-address"
is_child=yes
struct_name=da_vtn_ether_match
check_bool_set=yes
build_support=no
mandatory=yes
parse_support=yes

[src_arr]
type=string
key="source-address"
is_child=yes
struct_name=da_vtn_ether_match
check_bool_set=yes
build_support=no
mandatory=yes
parse_support=yes

[da_vtn_ether_match]
type=struct
key="vtn-ether-match"
is_child=no
struct_name=data_flow_match
members=dst_arr,src_arr,vlan,valid
check_bool_set=yes
build_support=no
mandatory=yes
parse_support=yes

[dscp]
type=int
key="dscp"
is_child=yes
struct_name=da_vtn_inet_match
check_bool_set=yes
build_support=no
mandatory=no
parse_support=yes

[protocol]
type=int
key="protocol"
is_child=yes
struct_name=da_vtn_inet_match
check_bool_set=yes
build_support=no
mandatory=no
parse_support=yes

[dst_ip]
type=string
key="destination-network"
is_child=yes
struct_name=da_vtn_inet_match
check_bool_set=yes
build_support=no
mandatory=no
parse_support=yes

[src_ip]
type=string
key="source-network"
is_child=yes
struct_name=da_vtn_inet_match
check_bool_set=yes
build_support=no
mandatory=no
parse_support=yes

[da_vtn_inet_match]
type=struct
key="vtn-inet-match"
is_child=no
struct_name=data_flow_match
members=dst_ip,src_ip,dscp,protocol,valid
check_bool_set=yes
build_support=no
mandatory=no
parse_support=yes

[data_flow_match]
type=struct
key="data-flow-match"
is_child=yes
struct_name=data_flow
members=da_vtn_ether_match,da_vtn_inet_match,valid
check_bool_set=yes
build_support=no
mandatory=yes
parse_support=yes

[eg_port_name]
type=string
key="port-name"
is_child=yes
struct_name=data_egress_port
check_bool_set=yes
build_support=no
mandatory=yes
parse_support=yes

[eg_port_id]
type=string
key="port-id"
is_child=yes
struct_name=data_egress_port
check_bool_set=yes
build_support=no
mandatory=yes
parse_support=yes

[eg_node]
type=string
key="node"
is_child=yes
struct_name=data_egress_port
check_bool_set=yes
build_support=no
mandatory=yes
parse_support=yes

[data_egress_port]
type=struct
key="data-egress-port"
is_child=yes
struct_name=data_flow
members=eg_node,eg_port_id,eg_port_name,valid
check_bool_set=yes
build_support=no
mandatory=yes
parse_support=yes

[eg_tenant]
type=string
key="tenant-name"
is_child=yes
struct_name=data_egress_node
check_bool_set=yes
build_support=no
mandatory=no
parse_support=yes

[eg_bridge]
type=string
key="bridge-name"
is_child=yes
struct_name=data_egress_node
check_bool_set=yes
build_support=no
mandatory=no
parse_support=yes

[eg_terminal]
type=string
key="terminal-name"
is_child=yes
struct_name=data_egress_node
check_bool_set=yes
build_support=no
mandatory=no
parse_support=yes

[eg_if]
type=string
key="interface-name"
is_child=yes
struct_name=data_egress_node
check_bool_set=yes
build_support=no
mandatory=no
parse_support=yes


[data_egress_node]
type=struct
key="data-egress-node"
is_child=yes
struct_name=data_flow
members=eg_bridge,eg_tenant,eg_if,eg_terminal,valid
check_bool_set=yes
build_support=no
mandatory=yes
parse_support=yes

[creation_time]
type=int
key="creation-time"
is_child=yes
struct_name=data_flow
build_support=no
mandatory=yes
parse_support=yes


[data_flow]
type=array
key="data-flow-info"
is_child=no
check_bool_set=no
struct_name=data_flow
members=creation_time,data_egress_node,data_egress_port,da_actions,data_flow_match,data_flow_stats,data_ingress_node,data_ingress_port,flow_id,hard_timeout,idle_timeout,physical_route,virtual_route,valid
build_support=no
mandatory=yes
parse_support=yes

[dataflows]
type=struct
key="output"
is_child=yes
check_bool_set=yes
struct_name=data_flow
members=data_flow
build_support=no
mandatory=yes
parse_support=yes

[ip_mac_addr]
type=string
key="mac-address"
is_child=no
check_bool_set=yes
struct_name=data_flow_source
build_support=yes
mandatory = no
parse_support=no

[ip_vlan]
type=int
key="vlan-id"
is_child=no
check_bool_set=yes
struct_name=data_flow_source
build_support=yes
mandatory = no
parse_support=no

[data_flow_source]
type=struct
key="data-flow-source"
is_child=no
check_bool_set=yes
struct_name=input_data_flow
members = ip_mac_addr,ip_vlan,valid
build_support=yes
mandatory = no
parse_support=no

[ip_port_name]
type=string
key="port-name"
is_child=no
check_bool_set=yes
struct_name=data_flow_port
build_support=yes
mandatory = no
parse_support=no

[ip_port_id]
type=string
key="port-id"
is_child=no
check_bool_set=yes
struct_name=data_flow_port
build_support=yes
mandatory = no
parse_support=no

[data_flow_port]
type=struct
key="data-flow-port"
is_child=no
check_bool_set=yes
struct_name=input_data_flow
members = ip_port_id,ip_port_name,valid
build_support=yes
mandatory = no
parse_support=no

[ip_flow_id]
type=int
key="flow-id"
is_child=no
check_bool_set=yes
struct_name=input_data_flow
build_support=yes
mandatory = no
parse_support=no

[ip_node]
type=string
key="node"
is_child=no
check_bool_set=yes
struct_name=input_data_flow
build_support=yes
mandatory = no
parse_support=no

[mode]
type=string
key="mode"
is_child=no
check_bool_set=yes
struct_name=input_data_flow
build_support=yes
mandatory = yes
parse_support=no

[ip_tenant_name]
type=string
key="tenant-name"
is_child=no
check_bool_set=yes
struct_name=input_data_flow
build_support=yes
mandatory = yes
parse_support=no

[input_data_flow]
type=struct
key="input"
is_child=no
check_bool_set=yes
struct_name=input_data_flow
members=ip_tenant_name,mode,ip_node,ip_flow_id,data_flow_port,data_flow_source,valid
build_support=yes
parse_support=no

[ip_dataflow]
type=struct
key="input"
is_child=no
check_bool_set=yes
struct_name=ip_dataflow
members=input_data_flow,valid
build_support=yes
parse_support=no

[ip_dataflows]
type=object
key="input"
is_child=no
check_bool_set=yes
struct_name=ip_dataflow
members=ip_dataflow
build_support=yes
parse_support=no


[dataflow_parser]
type = READ
request_type = object
parse_request_members = dataflows
build_request_members = ip_dataflows
get_req = yes
response_members = "dataflows"

[dataflow_class]
type = READ
interface = tenantName
request_type = object
request_members = dataflows
response_members = "dataflows"

[ROOT]
url_class = dataflow_class
parse_class = dataflow_parser
namespace = odcdriver
struct_type = ip_dataflow,data_flow 
data = phy_egr_port,phy_ingr_port,virt_node_path,virtual_route,physical_route,data_ingress_port,data_ingress_node,duration,data_flow_stats,vlan_id,da_actions,da_vtn_ether_match,da_vtn_inet_match,data_flow_match,data_egress_port,data_egress_node,data_flow,dataflows,data_flow_port,data_flow_source,input_data_flow,ip_dataflow
methods = dataflow_class
