# Copyright (c) 2016 NEC Corporation
# All rights reserved.
#
# This program and the accompanying materials are made available under the
# terms of the Eclipse Public License v1.0 which accompanies this
# distribution, and is available at http://www.eclipse.org/legal/epl-v10.html

[flowlistentry_class]
type=CU,DEL,READ
interface=cond_name
request_type=object
request_members=flowlistentrys
response_members="flowlistentrys"


[flowlistentry_parser]
type=CU,DEL,READ
request_type=object
build_request_members=ip_flowlistentrys
parse_request_members=flowlistentrys
response_members="flowlistentrys"

[CU]
url=FLOWLISTENTRY_COMANSUPPORT_URL

[READ]
url=FLOWLISTENTRY_GETSUPPORT_URL

[DEL]
url=FLOWLISTENTRY_DELSUPPORT_URL

[FLOWLISTENTRY_GETSUPPORT_URL]
type=url_string
url_format=BASEURL,SLASH,FLOWCONDITIONS,COLON,GET_FLOWCONDITION


[FLOWLISTENTRY_COMANSUPPORT_URL]
type=url_string
url_format=BASEURL,SLASH,FLOWCONDITIONS,COLON,CU_FLOWCONDITION

[FLOWLISTENTRY_DELSUPPORT_URL]
type=url_string
url_format=BASEURL,SLASH,FLOWCONDITIONS,COLON,DEL_FLOWCONDITION

[BASEURL]
type=url_string
value="/restconf/operations"

[SLASH]
type=url_string
value="/"

[COLON]
type=url_string
value=":"

[FLOWCONDITIONS]
type=url_string
value="vtn-flow-condition"

[GET_FLOWCONDITION]
type=url_string
value="vtn-flow-conditions"

[CU_FLOWCONDITION]
type=url_string
value="set-flow-condition-match"

[DEL_FLOWCONDITION]
type=url_string
value="remove-flow-condition-match"

[cond_name]
type=url_string
get_abstract=yes

[udp_dst_port_to]
type=string
key="port_to"
is_child=yes
struct_name=udp_destination_range
mandatory=no
build_support=yes
parse_support=no

[udp_dst_port_from]
type=string
key="port_from"
is_child=yes
struct_name=udp_destination_range
mandatory=no
build_support=yes
parse_support=no

[udp_destination_range]
type=struct
key="udp-destination-range"
is_child=yes
struct_name=match
members=udp_dst_port_from,udp_dst_port_to,valid
mandatory=no
build_support=yes
parse_support=no

[udp_src_port_to]
type=string
key="port_to"
is_child=yes
struct_name=udp_source_range
mandatory=no
build_support=yes
parse_support=no

[udp_src_port_from]
type=string
key="port_from"
is_child=yes
struct_name=udp_source_range
mandatory=no
build_support=yes
parse_support=no

[udp_source_range]
type=struct
key="tcp-source-range"
is_child=yes
struct_name=match
members=udp_src_port_from,udp_src_port_to,valid
mandatory=no
build_support=yes
parse_support=no

[dst_port_to]
type=string
key="port_to"
is_child=yes
struct_name=tcp_dest_range
mandatory=no
build_support=yes
parse_support=no

[dst_port_from]
type=string
key="port_from"
is_child=yes
struct_name=tcp_dest_range
mandatory=no
build_support=yes
parse_support=no

[tcp_src_range]
type=struct
key="tcp-source-range"
is_child=yes
struct_name=match
members=src_port_from,src_port_to,valid
mandatory=no
build_support=yes
parse_support=no


[tcp_dest_range]
type=struct
key="tcp-destination-range"
is_child=yes
struct_name=match
members=dst_port_from,dst_port_to,valid
mandatory=no
build_support=yes
parse_support=no

[src_port_to]
type=string
key="port-to"
is_child=yes
struct_name=tcp-source-range
mandatory=no
build_support=yes
parse_support=no


[src_port_from]
type=string
key="port-from"
is_child=yes
struct_name=tcp_src_range
mandatory=no
build_support=yes
parse_support=no

[tcp_src_range]
type=struct
key="tcp-source-range"
is_child=yes
struct_name=match
members=src_port_from,src_port_to,valid
mandatory=no
build_support=yes
parse_support=no

[icmp_code]
type=int
key="icmp-code"
is_child=yes
struct_name=match
mandatory=yes
build_support=yes
parse_support=no


[icmp_type]
type=int
key="icmp-type"
is_child=yes
struct_name=match
mandatory=no
build_support=yes
parse_support=no

[dscp]
type=int
key="dscp"
is_child=yes
struct_name=inet_match
mandatory=no
build_support=yes
parse_support=no

[protocol]
type=int
key="protocol"
is_child=yes
struct_name=inet_match
mandatory=no
build_support=yes
parse_support=no

[dest_network]
type=string
key="destination-network"
is_child=yes
struct_name=inet_match
mandatory=yes
build_support=yes
parse_support=no


[src_network]
type=string
key="source-network"
is_child=yes
struct_name=inet_match
mandatory=no
build_support=yes
parse_support=no

[ether_type]
type=int
key="ether-type"
is_child=yes
struct_name=ether_match
mandatory=yes
build_support=yes
parse_support=no

[vlanpri]
type=int
key="vlan-pcp"
is_child=yes
struct_name=ether_match
mandatory=no
build_support=yes
parse_support=no

[dest_addr]
type=string
key="destination-address"
is_child=yes
struct_name=ether_match
mandatory=no
build_support=yes
parse_support=no

[src_addr]
type=string
key="source-address"
is_child=yes
struct_name=ether_match
mandatory=no
build_support=yes
parse_support=no

[inet_match]
type=struct
key="vtn-inet-match"
is_child=yes
struct_name=inet_match
mandatory=no
members=src_network,dest_network,protocol,dscp,valid
build_support=yes
parse_support=no

[ether_match]
type=struct
key="vtn-ether-match"
is_child=yes
struct_name=match
members=src_addr,dest_addr,vlanpri,ether_type,valid
build_support=yes
mandatory=no
parse_support=no

[index]
type=int
key="index"
struct_name=match
mandatory=yes
build_support=yes
parse_support=no

[match]
type=array
key="vtn-flow-match"
is_child=yes
check_bool_set=no
struct_name=match
members=index,ether_match,inet_match,tcp_src_range,tcp_dest_range,icmp_type,icmp_code,udp_source_range,udp_destination_range,valid
build_support=yes
mandatory=yes
parse_support=no

[name]
type=string
key="name"
is_child=yes
check_bool_set=no
struct_name=flowlistentry
build_support=yes
mandatory=yes
parse_support=no

[operation]
type=string
key="operation"
is_child=yes
check_bool_set=no
struct_name=flowlistentry
build_support=yes
mandatory=yes
parse_support=no

[present]
type=bool
key="present"
is_child=yes
check_bool_set=no
struct_name=flowlistentry
build_support=yes
mandatory=yes
parse_support=no

[valid]
type=bool
key=""
struct_name=match
mandatory=no
build_support=no
parse_support=no

[in_flowcond]
type=struct
key="input"
is_child=yes
check_bool_set=no
struct_name = ip_flowlistentry
members= name,match,valid
build_support=yes
parse_support=no

[ip_flowlistentry]
type=struct
key="ip_flowlistentry"
is_child=yes
check_bool_set=yes
struct_name = ip_flowlistentry
members = in_flowcond,valid
build_support=yes
parse_support=no

[ip_flowlistentrys]
type=object
key="ip_flowlistentrys"
is_child=yes
check_bool_set=yes
struct_name = ip_flowlistentry
members = ip_flowlistentry
build_support=yes
parse_support=no

[flowlistentrys]
type=object
key="flowlistentrys"
is_child=no
check_bool_set=no
struct_name = ip_flowlistentry
members = ip_flowlistentry
build_support=no
parse_support=no


[ROOT]
url_class = flowlistentry_class
parse_class= flowlistentry_parser
namespace=odcdriver
struct_type = match,ip_flowlistentry
data=udp_source_range,udp_destination_range,tcp_src_range,tcp_dest_range,ether_match,inet_match,match,in_flowcond,ip_flowlistentry
methods= flowlistentry_class
