# Copyright (c) 2015-2016 NEC Corporation
# All rights reserved.
#
# This program and the accompanying materials are made available under the
# terms of the Eclipse Public License v1.0 which accompanies this
# distribution, and is available at http://www.eclipse.org/legal/epl-v10.html

[flowlist_class]
type=READ,CU,DEL
request_type=object
request_members=flowlists
response_members="flowlists"
http_success=201

[flowlist_parser]
type=READ,CU,DEL
request_type=object
parse_request_members=flowlists
build_request_members= ip_flowlists
response_members="flowlists"
http_success=200

[READ]
url=FLOWLIST_GETSUPPORT_URL

[CU]
url=FLOWLIST_COMANSUPPORT_URL

[DEL]
url=FLOWLIST_DELSUPPORT_URL

[FLOWLIST_DELSUPPORT_URL]
type=url_string
url_format=BASEURL,SLASH,DEL_FLOWCONDITION

[FLOWLIST_GETSUPPORT_URL]
type=url_string
url_format=GET_BASEURL,SLASH,GET_FLOWCONDITIONS


[FLOWLIST_COMANSUPPORT_URL]
type=url_string
url_format=BASEURL,SLASH,FLOWCONDITIONS

[GET_BASEURL]
type=url_string
value="/restconf/operational"

[BASEURL]
type=url_string
value="/restconf/operations"

[SLASH]
type=url_string
value="/"

[DEL_FLOWCONDITION]
type=url_string
value="vtn-flow-condition:remove-flow-condition"

[FLOWCONDITIONS]
type=url_string
value="vtn-flow-condition:set-flow-condition"

[GET_FLOWCONDITIONS]
type=url_string
value="vtn-flow-condition:vtn-flow-conditions"

[udp_dst_port_to]
type=string
key="port_to"
is_child=yes
struct_name=pa_udp_destination_range
mandatory=no
build_support=no
parse_support=no

[udp_dst_port_from]
type=string
key="port_from"
is_child=yes
struct_name=pa_udp_destination_range
mandatory=no
build_support=no
parse_support=no

[pa_udp_destination_range]
type=struct
key="udp-destination-range"
is_child=yes
struct_name=vtn_flow_match
members=udp_dst_port_from,udp_dst_port_to,valid
mandatory=no
build_support=no
parse_support=no

[udp_src_port_to]
type=string
key="port_to"
is_child=yes
struct_name=pa_udp_source_range
mandatory=no
build_support=no
parse_support=no

[udp_src_port_from]
type=string
key="port_from"
is_child=yes
struct_name=pa_udp_source_range
mandatory=no
build_support=no
parse_support=no

[pa_udp_source_range]
type=struct
key="tcp-source-range"
is_child=yes
struct_name=vtn_flow_match
members=udp_src_port_from,udp_src_port_to,valid
mandatory=no
build_support=no
parse_support=no

[dst_port_to]
type=int
key="port_to"
is_child=yes
struct_name=tcp_destination_range
mandatory=no
build_support=no
parse_support=yes

[dst_port_from]
type=int
key="port_from"
is_child=yes
struct_name=tcp_destination_range
mandatory=no
build_support=no
parse_support=yes

[tcp_source_range]
type=struct
key="tcp-source-range"
is_child=yes
struct_name=vtn_flow_match
members=src_port_from,src_port_to,valid
mandatory=no
build_support=no
parse_support=yes


[tcp_destination_range]
type=struct
key="tcp-destination-range"
is_child=yes
struct_name=vtn_flow_match
members=dst_port_from,dst_port_to,valid
mandatory=no
build_support=no
parse_support=yes

[src_port_to]
type=int
key="port-to"
is_child=yes
struct_name=tcp_source_range
mandatory=no
build_support=no
parse_support=yes


[src_port_from]
type=int
key="port-from"
is_child=yes
struct_name=tcp_source_range
mandatory=no
build_support=no
parse_support=yes

[tcp_source_range]
type=struct
key="tcp-source-range"
is_child=yes
struct_name=vtn_flow_match
members=src_port_from,src_port_to,valid
mandatory=no
build_support=no
parse_support=yes

[icmp_code]
type=int
key="icmp-code"
is_child=yes
struct_name=vtn_flow_match
mandatory=no
build_support=no
parse_support=yes


[icmp_type]
type=int
key="icmp-type"
is_child=yes
struct_name=vtn_flow_match
mandatory=no
build_support=no
parse_support=yes

[dscp]
type=int
key="dscp"
is_child=yes
struct_name=vtn_inet_match
mandatory=no
build_support=no
parse_support=yes

[protocol]
type=int
key="protocol"
is_child=yes
struct_name=vtn_inet_match
mandatory=no
build_support=no
parse_support=yes

[destination_network]
type=string
key="destination-network"
is_child=yes
struct_name=vtn_inet_match
mandatory=yes
build_support=no
parse_support=yes


[source_network]
type=string
key="source-network"
is_child=yes
struct_name=vtn_inet_match
mandatory=no
build_support=no
parse_support=yes

[ether_type]
type=int
key="ether-type"
is_child=yes
struct_name=vtn_ether_match
mandatory=no
build_support=no
parse_support=yes

[vlanpri]
type=int
key="vlan-pcp"
is_child=yes
struct_name=vtn_ether_match
mandatory=no
build_support=no
parse_support=yes

[destination_address]
type=string
key="destination-address"
is_child=yes
struct_name=vtn_ether_match
mandatory=no
build_support=no
parse_support=yes

[source_address]
type=string
key="source-address"
is_child=yes
struct_name=vtn_ether_match
mandatory=no
build_support=no
parse_support=yes

[vtn_inet_match]
type=struct
key="vtn-inet-match"
is_child=yes
struct_name=vtn_flow_match
mandatory=no
members=source_network,destination_network,protocol,dscp,valid
build_support=no
parse_support=yes

[vtn_ether_match]
type=struct
key="vtn-ether-match"
is_child=yes
struct_name=vtn_flow_match
members=source_address,destination_address,vlanpri,ether_type,valid
build_support=no
mandatory=no
parse_support=yes

[flow_index]
type=int
key="index"
struct_name=vtn_flow_match
mandatory=yes
build_support=no
parse_support=yes

[vtn_flow_match]
type=array
key="vtn-flow-match"
is_child=yes
check_bool_set=yes
struct_name=vtn_flow_match
members=flow_index,vtn_ether_match,vtn_inet_match,icmp_type,icmp_code,tcp_source_range,tcp_destination_range,pa_udp_source_range,pa_udp_destination_range,valid
build_support=no
mandatory=yes
parse_support=yes

[name]
type=string
key="name"
is_child=yes
check_bool_set=no
struct_name=flowlist
build_support=no
mandatory=yes
parse_support=yes

[valid]
type=bool
key=""
struct_name=vtn_flow_match
mandatory=no
build_support=no
parse_support=no

[flowlist]
type=array
key="vtn-flow-condition"
is_child=yes
check_bool_set=no
struct_name = flowlist
members= name,vtn_flow_match
mandatory=yes
build_support=no
parse_support=yes

[valid]
type=bool
key=""
struct_name=input_flowlist
mandatory=no
build_support=no
parse_support=no

[present]
type=bool
key="present"
is_child=yes
check_bool_set=no
struct_name=input_flowlist
build_support=yes
mandatory=yes
parse_support=no

[operation]
type=string
key="operation"
is_child=yes
check_bool_set=no
struct_name=input_flowlist
build_support=yes
mandatory=yes
parse_support=no

[ip_name]
type=string
key="name"
is_child=yes
check_bool_set=no
struct_name=input_flowlist
build_support=yes
mandatory=yes
parse_support=no

[input_flowlist]
type=struct
key="input"
is_child=yes
check_bool_set=yes
struct_name = ip_flowlist
members= ip_name,operation,present,valid
build_support = yes
parse_support = no

[ip_flowlist]
type=struct
key="ip_flowlist"
is_child=yes
check_bool_set=yes
struct_name = ip_flowlist
members= input_flowlist,valid
build_support = yes
parse_support = no

[ip_flowlists]
type=object
key="ip_flowlists"
is_child=yes
check_bool_set=yes
struct_name = ip_flowlist
members= ip_flowlist
build_support = yes
parse_support = no

[flowlists]
type=object
key="vtn-flow-conditions"
is_child=yes
check_bool_set=yes
struct_name = flowlist
members=flowlist

[ROOT]
url_class = flowlist_class
parse_class= flowlist_parser
namespace=odcdriver
struct_type = vtn_flow_match,flowlist,ip_flowlist
data=pa_udp_source_range,pa_udp_destination_range,tcp_source_range,tcp_destination_range,vtn_ether_match,vtn_inet_match,vtn_flow_match,flowlist,input_flowlist,ip_flowlist
methods= flowlist_class
