
[id]
type=string
key="id"
struct_name=vtn_node
build_support =no
parse_support=yes


[vtn_node]
type=array
key="vtn-node"
struct_name=vtn_node
check_bool_set=no
members=id

[vtn_nodes]
type=object
key="vtn-nodes"
struct_name=vtn_node
check_bool_set=yes
members=vtn_node


[RESTURL]
type=url_string
value="/restconf"

[SLASH]
type=url_string
value="/"

[VTNNODESURL]
type=url_string
value="vtn-nodes"

[VTNINVENTORYURL]
type=url_string
value="vtn-inventory"

[COLON]
type=url_string
value=":"

[OPERATIONURL]
type=url_string
value="operational"

[controller_ip]
type=string
get_abstract=yes

[controller_port]
type=string
get_abstract=yes


[VTN_GETSUPPORT_URL]
type=url_string
url_format=RESTURL,SLASH,OPERATIONURL,SLASH,VTNINVENTORYURL,COLON,VTNNODESURL
interface_members=controller_ip,controller_port


[vtn_nodes_parser]
type=READ
url=VTN_GETSUPPORT_URL
request_type=object
request_members=vtn_nodes
response_members="vtn-nodes"
http_success=200

[vtn_nodes_request]
type=READ
request_type=object
request_members=vtn_nodes
response_members="vtn-nodes"
http_success=200

[READ]
url=VTN_GETSUPPORT_URL



[ROOT]
url_class = vtn_nodes_request
parse_class=vtn_nodes_parser
namespace=odcdriver
struct_type = vtn_node
data=vtn_node
methods=vtn_nodes_request
