[index]
type=int
key=index
min=0
max=65535
ipc_struct=key_vbr_if_flowfilter_entry
ipc_name=sequence_num
category=mandatory
ipc_valid_flag=no
get_support=yes
set_support=yes
set_abstract=no
get_abstract=no

[condition]
type=string
key=condition
ipc_name=val_ff_entry.flowlist_name
category=mandatory
ipc_struct=pfcdrv_val_flowfilter_entry
ipc_valid_flag=yes
ipc_valid_enum=UPLL_IDX_SEQ_NUM_FFES
ipc_enum_compare_value=UNC_VF_VALID
get_support=yes
set_support=yes
set_abstract=no
get_abstract=no

[filterType]
type=object
key=filterType
category=not_mandatory
ipc_struct=pfcdrv_val_flowfilter_entry
ipc_name=valid
ipc_valid_flag=yes
ipc_valid_enum=UPLL_IDX_ACTION_FFE
ipc_enum_compare=yes
ipc_enum_compare_value=UNC_VF_VALID
members=pass,drop,redirect
get_support=yes
set_support=yes
set_abstract=no
get_abstract=no

[pass]
type=object
key=pass
ipc_struct=pfcdrv_val_flowfilter_entry
members=empty
ipc_name=val_ff_entry.action
ipc_valid_flag=yes
ipc_valid_enum=UPLL_FLOWFILTER_ACT_PASS
ipc_enum_compare=no
get_support=no
set_abstract=no
get_abstract=yes
set_support=yes
virtual_class_name=VirtParserVbrIfFlowfilterEntry

[drop]
type=object
key=drop
members=empty
ipc_struct=pfcdrv_val_flowfilter_entry
ipc_name=val_ff_entry.action
ipc_valid_flag=yes
ipc_valid_enum=UPLL_FLOWFILTER_ACT_DROP
ipc_enum_compare=no
get_support=no
get_abstract=yes
set_support=yes
set_abstract=no
virtual_class_name=VirtParserVbrIfFlowfilterEntry

[redirect]
type=object
key=redirect
members=destination,output
ipc_struct=pfcdrv_val_flowfilter_entry
ipc_name=val_ff_entry.action
ipc_valid_flag=yes
ipc_enum_compare=no
ipc_valid_enum=UPLL_FLOWFILTER_ACT_REDIRECT
get_support=no
get_abstract=yes
set_support=yes
set_abstract=no
virtual_class_name=VirtParserVbrIfFlowfilterEntry

[output]
type=bool
key=output
members=empty
category=mandatory
ipc_struct=pfcdrv_val_flowfilter_entry
ipc_name=val_ff_entry.redirect_direction
ipc_valid_flag=yes
ipc_valid_enum=UPLL_FLOWFILTER_DIR_IN
get_support=no
get_abstract=yes
set_support=yes
set_abstract=no
virtual_class_name=VirtParserVbrIfFlowfilterEntry

[destination]
type=object
key=destination
members=bridge,tenant,interface
ipc_struct=pfcdrv_val_flowfilter_entry
ipc_name=val_ff_entry.redirect_node
ipc_valid_flag=no
ipc_valid_enum=UPLL_FLOWFILTER_ACT_REDIRECT
get_support=no
get_abstract=yes
set_support=yes
set_abstract=no
virtual_class_name=VirtParserVbrIfFlowfilterEntry

[bridge]
type=string
key=bridge
members=empty
category=not_mandatory
ipc_struct=pfcdrv_val_flowfilter_entry
ipc_name=val_ff_entry.redirect_node
ipc_valid_flag=no
get_support=yes
set_support=yes
set_abstract=no
gat_abstract=no

[tenant]
type=string
key=tenant
members=empty
category=not_mandatory
ipc_struct=key_vbr_if_flowfilter_entry
ipc_name=flowfilter_key.if_key.vbr_key.vtn_key.vtn_name
ipc_valid_flag=no
get_support=yes
set_support=yes
set_abstarct=no
get_abstract=no

[interface]
type=string
key=interface
members=empty
category=not_mandatory
ipc_struct=pfcdrv_val_flowfilter_entry
ipc_name=val_ff_entry.redirect_port
ipc_valid_flag=no
get_support=yes
set_support=yes
set_abstract=no
get_abstract=no

[actions]
type=array
key=actions
ipc_struct=pfcdrv_val_flowfilter_entry
ipc_valid_flag=no
members=dlsrc,dldst,vlanpcp,dscp
ignored_members=inet4src,inet4dst,tpsrc,tpdst,icmptype,icmpcode
get_support=yes
set_support=yes
set_abstract=no
get_abstract=no

[dlsrc]
type=object
key=dlsrc
members=dlsrc_address
category=not_mandatory
ipc_struct=pfcdrv_val_flowfilter_entry
ipc_valid_flag=yes
ipc_name=val_ff_entry.valid
ipc_valid_enum=UPLL_IDX_MODIFY_SRC_MAC_FFE
ipc_enum_compare=yes
ipc_enum_compare_value=UNC_VF_VALID
get_support=yes
set_support=yes
set_abstract=no
get_abstract=no

[dlsrc_address]
type=string
key=address
members=empty
category=not_mandatory
ipc_struct=pfcdrv_val_flowfilter_entry
ipc_name=valid
category=mandatory
ipc_valid_flag=no
get_support=no
set_support=no
set_abstract=yes
get_abstract=yes
virtual_class_name=VirtParserVbrIfFlowfilterEntry

[dldst]
type=object
key=dldst
members=dldst_address
category=not_mandatory
ipc_struct=pfcdrv_val_flowfilter_entry
ipc_name=val_ff_entry.valid
ipc_valid_enum=UPLL_IDX_MODIFY_DST_MAC_FFE
ipc_valid_flag=yes
ipc_enum_compare=yes
ipc_enum_compare_value=UNC_VF_VALID
get_support=yes
set_support=yes
set_abstarct=no
get_abstarct=no

[dldst_address]
type=string
key=address
members=empty
category=not_mandatory
ipc_struct=pfcdrv_val_flowfilter_entry
ipc_name=valid
category=mandatory
ipc_valid_flag=no
get_support=no
set_support=no
set_abstract=yes
get_abstract=yes
virtual_class_name=VirtParserVbrIfFlowfilterEntry

[inet4src]
type=object
key=inet4src
members=inet4src_address
category=not_mandatory
ipc_struct=pfcdrv_val_flowfilter_entry
ipc_name=valid
ipc_valid_flag=no
get_support=yes
set_support=yes
set_abstract=yes
get_abstract=no

[inet4src_address]
key=address
members=empty
category=not_mandatory
ipc_struct=pfcdrv_val_flowfilter_entry
ipc_name=valid
category=mandatory
ipc_valid_flag=no
get_support=yes
set_support=yes
set_abstract=yes
get_abstract=no

[inet4dst]
type=object
key=inet4dst
members=inet4dst_address
ipc_struct=pfcdrv_val_flowfilter_entry
category=not_mandatory
ipc_name=valid
ipc_valid_flag=no
get_support=yes
set_support=yes
get_abstract=no
set_abstract=no

[inet4dst_address]
type=string
key=address
members=empty
ipc_struct=pfcdrv_val_flowfilter_entry
ipc_name=valid
category=mandatory
ipc_valid_flag=no
get_support=yes
set_support=yes
get_abstract=no
set_abstract=yes

[tpsrc]
type=object
key=tpsrc
members=tpsrc_port
category=not_mandatory
ipc_struct=pfcdrv_val_flowfilter_entry
ipc_name=valid
ipc_valid_flag=no
get_support=yes
set_support=yes
set_abstract=no
get_abstract=no

[tpsrc_port]
type=int
key=port
min=0
max=65535
members=empty
ipc_struct=pfcdrv_val_flowfilter_entry
ipc_name=valid
category=not_mandatory
ipc_valid_flag=no
get_support=yes
set_support=yes
get_abstract=no
set_abstract=no

[tpdst]
type=object
key=tpdst
members=tpdst_port
category=not_mandatory
ipc_struct=pfcdrv_val_flowfilter_entry
ipc_name=valid
ipc_valid_flag=no
get_support=yes
set_support=yes
set_abstract=no
get_abstract=no

[tpdst_port]
type=int
key=port
min=0
max=65535
members=empty
ipc_struct=pfcdrv_val_flowfilter_entry
ipc_name=valid
category=not_mandatory
ipc_valid_flag=no
get_support=yes
set_support=yes
set_abstract=yes
get_abstract=no

[icmptype]
type=object
key=icmptype
members=icmp_type
ipc_struct=pfcdrv_val_flowfilter_entry
ipc_name=valid
ipc_valid_flag=no
get_support=yes
set_support=yes
set_abstract=no
get_abstract=no

[icmp_type]
type=int
key=type
min=0
max=255
members=empty
ipc_struct=pfcdrv_val_flowfilter_entry
ipc_name=valid
category=not_mandatory
ipc_valid_flag=no
get_support=yes
set_support=yes
get_abstract=no
set_abstract=no

[icmpcode]
type=object
key=icmpcode
members=icmp_code
ipc_struct=pfcdrv_val_flowfilter_entry
ipc_name=valid
ipc_valid_flag=no
get_support=yes
set_support=yes

[icmp_code]
type=int
key=code
min=0
max=255
members=empty
ipc_struct=pfcdrv_val_flowfilter_entry
ipc_name=valid
category=not_mandatory
ipc_valid_flag=no
get_support=yes
set_support=yes


[vlanpcp]
type=object
key=vlanpcp
ipc_struct=pfcdrv_val_flowfilter_entry
ipc_valid_flag=yes
ipc_name=val_ff_entry.valid
ipc_valid_enum=UPLL_IDX_PRIORITY_FFE
ipc_enum_compare=yes
ipc_enum_compare_value=UNC_VF_VALID
members=vlanpcp_priority
get_support=yes
set_support=yes

[vlanpcp_priority]
type=int
key=priority
category=mandatory
ipc_struct=pfcdrv_val_flowfilter_entry
ipc_valid_flag=no
ipc_name=val_ff_entry.priority
min=0
max=7
get_support=yes
set_support=yes

[dscp]
type=object
key=dscp
ipc_struct=pfcdrv_val_flowfilter_entry
ipc_valid_flag=yes
ipc_valid_enum=UPLL_IDX_DSCP_FFE
ipc_enum_compare=yes
ipc_enum_compare_value=UNC_VF_VALID
ipc_name=val_ff_entry.valid
members=dscp_dscp
get_support=yes
set_support=yes

[dscp_dscp]
type=int
category=mandatory
key=dscp
ipc_struct=pfcdrv_val_flowfilter_entry
ipc_valid_flag=no
ipc_name=val_ff_entry.dscp
min=0
max=63
get_support=yes
set_support=yes

[flowfilter]
type=object
members=index,condition,filterType,actions
get_support=yes
set_support=yes
set_abstract=yes

[flowfilters]
key=flowfilter
type=list
item=flowfilter
parent_name=flowfilter_key.if_key.vbr_key.vtn_key.vtn_name
parent_name1=flowfilter_key.if_key.vbr_key.vbridge_name
parent_name2=flowfilter_key.if_key.if_name
set_support=yes
get_support=yes
set_abstract=yes

[extra_para]                                                                      
get_extra_argument=unc::driver::controller* ctr                                   
extra_parameter=empty
filterlist=yes

[para_constructor]
args=parent_name,parent_name1,parent_name2,redirect_node
data_type=std::string,std::string,std::string,std::string

[virtual_method]                                                                  
virtual_class_name=VirtParserVbrIfFlowfilterEntry 
get_virtual_method=empty 

[get_fill_portmap]
get_fill_portmaps=empty
portmaps=no

[code]
namespace=odcdriver

[additional_header]
header=#include <odl_virtual_vbrif_flowfilter.hh>

[class]
name=ParseVbrIfFlowfilter
parameterized_constructor=yes
set_method=create_vbr_if_flowfilter_request
set_sections=flowfilter
get_method=parse_vbr_if_flowfilter_response
get_sections=flowfilters
rest_type=json_object
ipc_key_struct=key_vbr_if_flowfilter_entry
ipc_val_struct=pfcdrv_val_flowfilter_entry
get_abstract=yes
set_abstract=yes
