[vtn_name]
type=string
key=name
ipc_struct=key_vtn_t
ipc_name=vtn_name
ipc_valid_flag=no
category=mandatory
get_support=yes
set_support=no
set_abstract=no
get_abstract=no

[vtn_description]
type=string
key=description
ipc_struct=val_vtn_t
ipc_name=description
category=not_mandatory
ipc_valid_flag=yes
ipc_valid_enum=UPLL_IDX_DESC_VTN
get_support=yes
set_support=yes
set_abstract=no
get_abstract=no

[vtn_idletime]
type=int
key=idleTimeout
min=0
max=65535
ipc_valid_flag=no
ipc_name=vtn_idletime
ipc_struct=val_vtn_t
category=not_mandatory
get_support=no
set_support=no
set_abstract=yes
get_abstract=no
virtual_class_name= VirtualVtnCommand

[vtn_hardtime]
type=int
key=hardTimeout
min=0
max=65535
ipc_valid_flag=no
ipc_struct=val_vtn_t
ipc_name=vtn_hardtime
category=not_mandatory
get_support=no
set_support=no
set_abstract=yes
get_abstract=no
virtual_class_name= VirtualVtnCommand

[vtn]
type=object
members=vtn_name,vtn_description,vtn_idletime,vtn_hardtime
get_support=yes
set_support=yes

[vtns]
key=vtn
type=list
item=vtn
parent_name=empty
parent_name1=empty
parent_name2=empty
get_abstract=yes
get_support=yes

[additional_header]
header=#include<odl_virtual_vtn.hh>

[para_constructor]
args=null
data_type=null

[virtual_method]
virtual_class_name=empty
get_virtual_method=empty

[extra_para]
get_extra_argument=empty
extra_parameter=no
filterlist=no

[get_fill_portmap]
get_fill_portmaps=empty
portmaps=no


[code]
namespace=odcdriver

[class]
name=VtnParser
parameterized_constructor=no
set_method=create_vtn_request
set_sections=vtn
get_method=parse_vtn_response
get_sections=vtns
rest_type=json_object
ipc_key_struct=key_vtn_t
ipc_val_struct=val_vtn_t
