[index]
type=int
key=index
min=1
max=65535
ipc_struct=key_vtn_flowfilter_entry
ipc_name=sequence_num
category=mandatory
ipc_valid_flag=no
get_support=yes
set_support=yes
set_abstract=no
get_abstract=no

[condition]
type=string
key=condition
ipc_name=flowlist_name
category=mandatory
ipc_struct=val_vtn_flowfilter_entry
ipc_valid_flag=yes
ipc_valid_enum=UPLL_IDX_SEQ_NUM_FFES
ipc_enum_compare_value=UNC_VF_VALID
get_support=yes
set_support=yes
set_abstract=no
get_abstract=no

[filterType]
type=object
key=filterType
category=not_mandatory
ipc_struct=val_vtn_flowfilter_entry
ipc_name=valid
ipc_valid_flag=yes
ipc_enum_compare=yes
ipc_valid_enum=UPLL_IDX_ACTION_VFFE
ipc_enum_compare_value=UNC_VF_VALID
members=pass,drop
get_support=yes
set_support=yes
set_abstract=no
get_abstract=no

[pass]
type=object
key=pass
ipc_struct=val_vtn_flowfilter_entry
members=empty
ipc_name=action
ipc_valid_flag=yes
ipc_valid_enum=UPLL_FLOWFILTER_ACT_PASS
ipc_enum_compare=no
get_support=no
get_abstract=yes
set_support=yes
set_abstract=no
virtual_class_name=VirtParserVtnFlowfilter

[drop]
type=object
key=drop
members=empty
ipc_struct=val_vtn_flowfilter_entry
ipc_name=action
ipc_valid_flag=yes
ipc_valid_enum=UPLL_FLOWFILTER_ACT_DROP
ipc_enum_compare=no
get_support=no
get_abstract=yes
set_support=yes
set_abstract=no
virtual_class_name=VirtParserVtnFlowfilter

[actions]
type=array
key=action
ipc_struct=val_vtn_flowfilter_entry
ipc_valid_flag=no
members=dscp,vlanpcp
get_support=yes
set_support=yes
set_abstract=no
get_abstract=no

[vlanpcp]
type=object
key=vlanpcp
ipc_struct=val_vtn_flowfilter_entry
ipc_valid_flag=yes
ipc_name=valid
ipc_valid_enum=UPLL_IDX_PRIORITY_VFFE
ipc_enum_compare=yes
ipc_enum_compare_value=UNC_VF_VALID
members=vlanpcp_priority
get_support=yes
set_support=yes
set_abstract=no
get_abstract=no

[vlanpcp_priority]
type=int
key=priority
category=mandatory
ipc_struct=val_vtn_flowfilter_entry
ipc_valid_flag=no
ipc_name=priority
min=0
max=7
get_support=yes
set_support=yes
set_abstract=no
get_abstract=no

[dscp]
type=object
key=dscp
ipc_struct=val_vtn_flowfilter_entry
ipc_valid_flag=yes
ipc_valid_enum=UPLL_IDX_DSCP_VFFE
ipc_enum_compare=yes
ipc_enum_compare_value=UNC_VF_VALID
ipc_name=valid
members=dscp_dscp
get_support=yes
set_support=yes
set_abstract=no
get_abstract=no

[dscp_dscp]
type=int
category=mandatory
key=dscp
ipc_struct=val_vtn_flowfilter_entry
ipc_valid_flag=no
ipc_name=dscp
min=0
max=63
get_support=yes
set_support=yes
set_abstract=no
get_abstract=no

[flowfilter]
type=object
members=index,condition,filterType,actions
ipc_valid_flag=yes
get_support=yes
set_support=yes
set_abstract=no
get_abstract=no

[flowfilters]
key=flowfilter
type=list
item=vtn_flowfilter
get_support=yes
set_support=yes
set_abstract=no
get_abstract=no
parent_name=flowfilter_key.vtn_key.vtn_name
parent_name1=empty
parent_name2=empty

[extra_para]
get_extra_argument=unc::driver::controller* ctr
extra_parameter=empty
filterlist=yes

[virtual_method]
virtual_class_name=VirtParserVtnFlowfilter
get_virtual_method=empty

[para_constructor]
args=parent_name
data_type=std::string

[get_fill_portmap]
get_fill_portmaps=empty
portmaps=no

[code]
namespace=odcdriver

[additional_header]
header=#include <odl_virtual_vtn_flowfilter.hh>

[class]
name=VtnFlowfilterParser
parameterized_constructor=yes
set_method=create_vtn_flowfilter_request
set_sections=flowfilter
get_method=parse_vtn_flowfilter_response
get_sections=flowfilters
rest_type=json_object
ipc_key_struct=key_vtn_flowfilter_entry
ipc_val_struct=val_vtn_flowfilter_entry
