[flowlist_name]
type=string
members=empty
ipc_struct=key_flowlist_t
key=name
ipc_name=flowlist_name
category=mandatory
ipc_valid_flag=no
get_support=yes
set_support=yes
set_abstract=no
get_abstract=no

[ip_type]
type=int
members=empty
ipc_struct=key_flowlist_t
key=name
ipc_name=ip_type
category=mandatory
ipc_valid_flag=no
get_support=no
set_support=no
set_abstract=no
get_abstract=yes
virtual_class_name=VirtParserFlowlist

[match]
type=array
members=empty
ipc_struct=key_flowlist_t
key=match
ipc_name=flow_match
category=mandatory
ipc_valid_flag=no
get_support=no
set_support=yes
get_abstract=no
set_abstract=no

[flowcondition]
type=object
members=flowlist_name,ip_type,match
get_support=yes
set_support=yes
set_abstract=no
get_abstract=no
get_abstract=no

[flowconditions]
key=flowcondition
type=object
parent_name=empty
parent_name1=empty
parent_name2=empty
get_support=yes
set_support=yes
set_abstract=no
get_abstract=no


[virtual_method]
virtual_class_name=empty
get_virtual_method=empty

[get_fill_portmap]
get_fill_portmaps=empty
portmaps=no

[extra_para]
get_extra_argument=empty
extra_parameter=empty
filterlist=no

[para_constructor]
args=null
data_type=null



[code]
namespace=odcdriver

[additional_header]
header=#include <odl_virtual_flowlist.hh>

[class]
name=FlowlistParser
parameterized_constructor=no
set_method=create_flowlist_request
set_sections=flowcondition
get_method=parse_flowlist_response
get_sections=flowconditions
rest_type=json_object
ipc_key_struct=key_flowlist_t
ipc_val_struct=val_flowlist_t
