[vterm_if_name]
type=string
key=name
ipc_struct=key_vterm_if_t
ipc_name=if_name
category=mandatory
ipc_valid_flag=no
get_support=yes
set_support=no
get_abstract=no
set_abstract=no

[vterm_if_description]
type=string
key=description
ipc_struct=val_vterm_if_t
ipc_name=description
category=not_mandatory
ipc_valid_flag=yes
ipc_valid_enum=UPLL_IDX_DESC_VTERMI
get_support=yes
set_support=yes
set_abstract=no
get_abstract=no

[vterm_if_enabled]
type=boolean
key=enabled
ipc_struct=val_vterm_if_t
ipc_name=description
ipc_valid_flag=no
value=true
category=mandatory
get_support=no
set_support=no
get_abstract=yes
set_abstract=yes
virtual_class_name=VirtParserOdcVtermIfCmd


[interface]
type=object
members=vterm_if_name,vterm_if_description,vterm_if_enabled
get_support=yes
set_support=yes

[interfaces]
key=interface
type=list
parent_name =vterm_key.vtn_key.vtn_name
parent_name1=vterm_key.vterminal_name
parent_name2=empty
item=interface
get_support=yes
set_support=yes
get_abstract=yes
set_abstract=yes

[extra_para]
get_extra_argument=unc::driver::controller* ctr, unc::restjson::ConfFileValues_t conf_values_
extra_parameter=yes
filterlist=no

[para_constructor]
args=parent_name,parent_name1,url_
data_type=std::string,std::string,std::string

[virtual_method]
virtual_class_name=empty
get_virtual_method=empty

[additional_header]
header=#include<odl_virt_parser_vtermif.hh>

[get_fill_portmap]
get_fill_portmaps=yes
virt_class_name=VirtParserOdcVtermIfCmd

portmaps=no


[code]
namespace=odcdriver


[class]
name=VtermifParser
parameterized_constructor=yes
set_method=create_vterm_if_request
set_sections=interface
get_method=parse_vterm_if_response
get_sections=interfaces
rest_type=json_object
ipc_key_struct=key_vterm_if_t
ipc_val_struct=val_vterm_if_t


