[match]
type=array
key=match
members=index,ethernet,inetMatch,l4Match
ipc_struct=val_flowflist_entry_t
ipc_name=flow_match
set_match=no
category=mandatory
ipc_valid_flag=no
get_support=yes
set_support=no
set_abstract=no
get_abstract=no

[index]
type=int
key=index
memebers=empty
min=0
max=65535
ipc_struct=key_flowlist_entry_t
ipc_name=sequence_num
category= mandatory
ipc_valid_flag=no
get_support=yes
set_support=yes
set_abstract=no
get_abstract=no

[Index]
type=int
key=index
memebers=empty
min=0
max=65535
ipc_struct=key_flowlist_entry_t
ipc_name=sequence_num
category= mandatory
ipc_valid_flag=no
get_support=no
set_support=yes
set_abstract=no
get_abstract=no

[ethernet]
type=object
key=ethernet
members=ethernet_src,ethernet_dst,ethernet_type,ethernet_vlanpri
ipc_struct=val_flowlist_entry_t
ipc_name=ethernet
category=mandatory
ipc_valid_flag=no
get_support=yes
set_support=yes
get_abstract=no
set_abstract=no

[Ethernet]
type=object
key=ethernet
members=ethernet_src,ethernet_dst,ethernet_type,ethernet_vlanpri
ipc_struct=val_flowlist_entry_t
ipc_name=ethernet
category=mandatory
ipc_valid_flag=no
get_support=no
set_support=yes
get_abstract=no
set_abstract=no



[ethernet_src]
type=string
key=src
members=empty
ipc_struct=val_flowlist_entry_t
ipc_name=mac_src[0]
category=mandatory
ipc_valid_flag=yes
ipc_valid_enum=UPLL_IDX_MAC_SRC_FLE
get_support=no
get_abstract=yes
set_support=no
set_abstract=yes
virtual_class_name=VirtParserFlowlistEntry



[ethernet_dst]
type=string
key=dst
members=empty
ipc_struct=val_flowlist_entry_t
ipc_name=mac_dst[0]
category=mandatory
ipc_valid_flag=yes
ipc_valid_enum=UPLL_IDX_MAC_DST_FLE
set_support=no
set_abstract=yes
get_support=no
get_abstract=yes
virtual_class_name=VirtParserFlowlistEntry



[ethernet_type]
type=int
key=type
min=0
max=65535
members=empty
ipc_struct=val_flowlist_entry_t
ipc_name=mac_eth_type
category=mandatory
ipc_valid_flag=yes
ipc_valid_enum=UPLL_IDX_MAC_ETH_TYPE_FLE
get_support=yes
set_support=yes
set_abstract=no
get_abstract=no


[ethernet_vlan]
type=int
key=vlan
min=0
max=4095
members=empty
ipc_struct=val_flowlist_entry_t
ipc_name=empty
category=mandatory
ipc_valid_flag=no
get_support=no
set_support=no
get_abstract=yes
set_abstract=yes
virtual_class_name=VirtParserFlowlistEntry



[ethernet_vlanpri]

type=int

key=vlanpri

min=0

max=7

members=empty

ipc_struct=val_flowlist_entry_t

ipc_name=vlan_priority

ipc_valid_flag=yes

ipc_valid_enum=UPLL_IDX_VLAN_PRIORITY_FLE

category=mandatory

get_support=yes

set_support=yes

set_abstract=no
get_abstract=no

[inetMatch]

type=object

key=inetMatch

members=inet4

ipc_struct=val_flowlist_entry_t

ipc_name=inetmatch

category=mandatory

ipc_valid_flag=no

get_support=yes

set_support=yes
set_abstract=no
get_abstract=no


[InetMatch]

type=object

key=inetMatch

members=inet4

ipc_struct=val_flowlist_entry_t

ipc_name=inetmatch

category=mandatory

ipc_valid_flag=no

get_support=no

set_support=yes
set_abstract=no
get_abstract=no
[inet4]

type=object

key=inet4

members=inet4_src,inet4_srcsuffix,inet4_dst,inet4_dstsuffix,inet4_protocol,inet4_dscp

ipc_struct=val_flowlist_entry_t

ipc_name=inet4

category=mandatory

ipc_valid_flag=no

get_support=yes

set_support=yes
set_abstract=no
get_abstract=no


[inet4_srcsuffix]

type=int

key=srcsuffix

min=1

max=31

members=empty

ipc_struct=val_flowlist_entry_t

ipc_name=src_ip_prefixlen

category=mandatory

ipc_valid_flag=yes

ipc_valid_enum=UPLL_IDX_SRC_IP_PREFIX_FLE

get_support=yes

set_support=yes

set_abstract=no
get_abstract=no

[inet4_dstsuffix]

type=int

key=dstsuffix

min=1

max=31

members=empty

ipc_struct=val_flowlist_entry_t

ipc_name=dst_ip_prefixlen

category=mandatory

ipc_valid_flag=yes

ipc_valid_enum=UPLL_IDX_DST_IP_PREFIX_FLE

get_support=yes

set_support=yes
set_abstract=no
get_abstract=no



[inet4_protocol]

type=int

key=protocol

min=0

max=255

members=empty

ipc_struct=val_flowlist_entry_t

ipc_name=ip_proto

category=mandatory

ipc_valid_flag=yes

ipc_valid_enum=UPLL_IDX_IP_PROTOCOL_FLE

get_support=yes

set_support=yes
set_abstract=no
get_abstract=no



[inet4_dscp]

type=int

key=dscp

min=0

max=63

members=empty

ipc_struct=val_flowlist_entry_t

ipc_name=ip_dscp

category=mandatory

ipc_valid_flag=yes

ipc_valid_enum=UPLL_IDX_IP_DSCP_FLE

get_support=yes

set_support=yes
set_abstract=no
get_abstract=no



[inet4_dst]

type=string

key=dst

members=empty

ipc_struct=val_flowlist_entry_t

ipc_name=dst_ip

category=mandatory

ipc_valid_flag=yes

ipc_valid_enum=UPLL_IDX_DST_IP_FLE

get_support=no
get_abstract=yes
set_support=no
set_abstract=yes
virtual_class_name=VirtParserFlowlistEntry



[inet4_src]

type=string

key=src

members=empty

ipc_struct=val_flowlist_entry_t

ipc_name=src_ip

category=mandatory

ipc_valid_flag=yes

ipc_valid_enum=UPLL_IDX_SRC_IP_FLE

get_support=no
get_abstract=yes
set_support=no
set_abstract=yes
virtual_class_name=VirtParserFlowlistEntry

[l4match]

type=object

key=L4match

members=l4Match_icmp,l4Match_tcp

ipc_struct=val_flowlist_entry_t

ipc_name=l4Match

category=mandatory

ipc_valid_flag=no

get_support=no

set_support=yes
set_abstract=no
get_abstract=no


[l4Match]

type=object

key=L4match

members=l4Match_icmp,l4Match_tcp

ipc_struct=val_flowlist_entry_t

ipc_name=l4Match

category=mandatory

ipc_valid_flag=no

get_support=yes

set_support=yes
set_abstract=no
get_abstract=no



[l4Match_icmp]

type=object

key=icmp

members=icmp_type,icmp_code

ipc_struct=val_flowlist_entry_t

ipc_name=icmp

category=mandatory

ipc_valid_flag=no

get_support=yes

set_support=yes

set_abstract=no
get_abstract=no


[icmp_type]

type=int

key=type

min=0

max=255

members=empty

ipc_struct=val_flowlist_entry_t

ipc_name=icmp_type

category=mandatory

ipc_valid_flag=yes

ipc_valid_enum=UPLL_IDX_ICMP_TYPE_FLE

get_support=yes

set_support=yes
set_abstract=no
get_abstract=no



[icmp_code]

type=int

key=code

min=0

max=255

members=empty

ipc_struct=val_flowlist_entry_t

ipc_name=icmp_code

category=mandatory

ipc_valid_flag=yes

ipc_valid_enum=UPLL_IDX_ICMP_CODE_FLE

get_support=yes

set_support=yes
set_abstract=no
get_abstract=no



[l4Match_tcp]

type=object

key=tcp

members=tcp_src,tcp_dst

ipc_struct=val_flowlist_entry_t

ipc_name=tcp

category=mandatory

ipc_valid_flag=no

get_support=yes

set_support=yes
set_abstract=no
get_abstract=no



[tcp_src]

type=object

key=src

members=src_from,src_to

ipc_struct=val_flowlist_entry_t

ipc_name=src

category=mandatory

ipc_valid_flag=no

get_support=yes

set_support=yes
set_abstract=no
get_abstract=no



[src_from]

type=int

key=from

min=0

max=65535

members=empty

ipc_struct=val_flowlist_t

ipc_name=l4_src_port

category=mandatory

ipc_valid_flag=yes

ipc_valid_enum=UPLL_IDX_L4_SRC_PORT_FLE

get_support=yes

set_support=yes
set_abstract=no
get_abstract=no



[src_to]

type=int

key=to

min=0

max=65535

members=empty

ipc_struct=val_flowlist_entry_t

ipc_name=l4_src_port_endpt

category=not mandatory

ipc_valid_flag=yes

ipc_valid_enum=UPLL_IDX_L4_SRC_PORT_ENDPT_FLE

get_support=yes

set_support=yes
set_abstract=no
get_abstract=no



[tcp_dst]

type=object

key=dstkey

members=dst_from,dst_to

ipc_struct=val_flowlist_entry_t

ipc_name=l4_dst_port

category=mandatory

ipc_valid_flag=no

get_support=yes

set_support=yes
set_abstract=no
get_abstract=no



[dst_from]

type=int

key=from

min=0

max=65535

members=empty

ipc_struct=val_flowlist_entry_t

ipc_name=l4_dst_port
category=mandatory
ipc_valid_flag=yes
ipc_valid_enum=UPLL_IDX_L4_DST_PORT_FLE
get_support=yes
set_support=yes
set_abstract=no
get_abstract=no



[dst_to]
type=int
key=to
min=0
max=65535
members=empty
ipc_struct=val_flowlist_entry_t
ipc_name=l4_dst_port_endpt
category=mandatory
ipc_valid_flag=yes

ipc_valid_enum=UPLL_IDX_L4_DST_PORT_ENDPT_FLE

get_support=yes
set_support=yes
set_abstract=no
get_abstract=no



[name]
type=string
members=empty
ipc_struct=key_flowlist_entry_t
key=name
ipc_name=flowlist_key.flowlist_name
category=mandatory

ipc_valid_flag=no

get_support=yes

set_support=yes
set_abstract=no
get_abstract=no



[flowcondition]
type=object
members=name,match,Index,Ethernet,InetMatch
get_support=yes
set_support=yes
set_abstract=no
get_abstract=no



[flowconditions]
key=flowlist
type=list
item=flowlists
parent_name=empty
parent_name1=empty
parent_name2=empty
set_support=yes
get_support=yes
set_abstract=no
get_abstract=no


[virtual_method]
virtual_class_name=VirtParserFlowlistEntry
get_virtual_method=empty

[get_fill_portmap]
get_fill_portmaps=empty
portmaps=no

[extra_para]
get_extra_argument=empty
extra_parameter=empty
filterlist=no

[para_constructor]
args=parent_name
data_type=std::string

[code]
namespace=odcdriver

[additional_header]
header=#include <odl_virtual_flowlist_entry.hh>

[class]
name=FlowlistEntryParser
parameterized_constructor=no
set_method=create_flowlist_entry_request
set_sections=flowcondition
get_method=parse_flowlist_entry_response
get_sections=flowconditions
rest_type=json_object
ipc_key_struct=key_flowlist_entry_t
ipc_val_struct=val_flowlist_entry_t
