[vbridge_name]
type=string
key=name
ipc_struct=key_vbr_t
ipc_name=vbridge_name
category=mandatory
ipc_valid_flag=no
category=mandatory
get_support=yes
set_support=no
get_abstract=no
set_abstract=no

[vbridge_description]
type=string
key=description
ipc_struct=val_vbr_t
ipc_name=vbr_description
ipc_valid_flag=yes
category=mandatory
ipc_valid_enum=UPLL_IDX_DESC_VBR
get_support=yes
set_support=yes
get_abstract=no
set_abstract=no

[vbridge_ageinterval]
type=int
key=ageinterval
min=10
max=1000000
ipc_valid_flag=no
category=mandatory
ipc_name=ageinterval
ipc_struct=val_vbr_t
get_support=no
set_support=no
get_abstract=no
set_abstract=yes
virtual_class_name=VirtualVbrCommand

[vbridge_faults]
type=int
key=faults
count=0
ipc_valid_flag=no
category=mandatory
ipc_name=faults
ipc_struct=val_vbr_t
get_support=no
set_support=no
get_abstract=no
set_abstract=no
virtual_class_name=VirtulVbrCommand

[vbridge_state]
type=int
key=state
min=-1
max=1
ipc_valid_flag=no
category=mandatory
ipc_name=state
ipc_struct=val_vbr_t
get_support=no
set_support=no
get_abstract=no
set_abstract=no
virtual_class_name=VirtualVbrCommand

[vbridge]
type=object
members=vbridge_name,vbridge_description,vbridge_ageinterval,vbridge_faults,vbridge_state
get_support=yes
set_support=yes

[vbridges]
key=vbr
type=object
parent_name=vtn_key.vtn_name
parent_name1=empty
parent_name2=empty
item=vbridge
set_support=yes
get_support=yes

[extra_para]
get_extra_argument=unc::driver::controller* ctr
extra_parameter=yes
filterlist=no
[para_constructor]
args=parent_name,controller_name,domain_name
data_type=std::string,std::string,std::string

[virtual_method]
get_virtual_method_name=virtual_method
get_virtual_members=controller_name,domain_name
virtual_class_name=VirtualVbrCommand
get_virtual_method=yes

[additional_header]
header=#include<odl_virtual_vbridge.hh>

[get_fill_portmap]
get_fill_portmaps=empty
portmaps=no

[code]
namespace=odcdriver

[class]
name=VbrParser
parameterized_constructor=yes
set_method=create_vbr_request
set_sections=vbridge
get_method=parse_vbr_response
get_sections=vbridges
rest_type=json_object
ipc_key_struct=key_vbr_t
ipc_val_struct=val_vbr_t

