[node]
type=object
key=node
ipc_name=node
members=type,id
ipc_valid_flag=no
ipc_struct=val_vterm_if_t
category=mandatory
ipc_valid_flag=no
get_support=yes
set_support=yes
get_abstract=yes
set_abstract=no

[type]
type=string
key=type
ipc_name=type
members=empty
ipc_valid_flag=no
ipc_struct=val_vterm_if_t
category=mandatory
set_support=no
get_support=no
set_abstract=yes
get_abstract=yes
virtual_class_name=VirtParserVtermifPortmapCmd

[id]
type=string
key=id
ipc_name=switch_id
members=empty
ipc_valid_flag=no
ipc_struct=val_vterm_if_t
category=mandatory
set_support=no
get_support=no
set_abstract=yes
get_abstract=yes
virtual_class_name=VirtParserVtermifPortmapCmd

[port]
type=object
key=port
ipc_name=port_name
members=name
ipc_struct=val_vterm_if_t
category=mandatory
ipc_valid_flag=no
get_support=yes
set_support=yes
get_abstract=yes
set_abstract=no
virtual_class_name=VirtParserVtermifPortmapCmd

[name]
type=string
key=name
ipc_name=name
members=empty
ipc_valid_flag=no
ipc_struct=val_vterm_if_t
category=mandatory
set_support=no
get_support=no
set_abstract=yes
get_abstract=yes
virtual_class_name=VirtParserVtermifPortmapCmd

[vlan]
type=int
key=vlan
ipc_struct=val_vterm_if_t
ipc_name=val_vtermif.portmap.vlan
category=mandatory
ipc_valid_flag=yes
ipc_valid_enum=UPLL_IDX_VLAN_ID_PM
get_support=no
set_support=no
get_abstract=yes
set_abstract=yes
virtual_class_name=VirtParserVtermifPortmapCmd


[portmap]
type=object
members=node,port,vlan
get_support=yes
set_support=yes

[portmaps]
key=portmap
type=list
parent_name=empty
parent_name1=empty
parent_name2=empty
item=portmap
get_abstract=yes
get_support=yes

[extra_para]
get_extra_argument=unc::driver::controller* ctr
extra_parameter=empty
filterlist=no
[additional_header]
header=#include <odl_virt_parser_vtermif_portmap.hh>

[get_fill_portmap]
get_fill_portmaps=empty
portmaps=yes

[virtual_method]
virtual_class_name=empty
get_virtual_method=empty

[para_constructor]
args=null
data_type=null

[code]
namespace=odcdriver

[class]
name=VtermifportmapParser
parameterized_constructor=no
set_method=create_vterm_if_portmap_request
set_sections=portmap
get_method=parse_vterm_if_portmap_response
get_sections=portmaps
rest_type=json_object
ipc_key_struct=key_vterm_if_t
ipc_val_struct=val_vterm_if_t
set_abstract=no
get_abstract=yes
