[vterminal_name]
type=string
key=name
ipc_struct=key_vterm_t
ipc_name=vterminal_name
category=mandatory
ipc_valid_flag=no
category=mandatory
get_support=yes
set_support=no
get_abstract=no
set_abstract=no

[vterminal_description]
type=string
key=description
ipc_struct=val_vterm_t
ipc_name=vterm_description
ipc_valid_flag=yes
category=mandatory
ipc_valid_enum=UPLL_IDX_DESC_VBR
get_support=yes
set_support=yes
get_abstract=no
set_abstract=no

[vterminal_faults]
type=int
key=faults
count=0
ipc_name=valid
ipc_valid_flag=no
category=mandatory
get_support=no
set_support=no
get_abstract=no
set_abstract=no
virtual_class_name=null

[vterminal_state]
type=int
key=state
min=-1
max=1
ipc_name=valid
ipc_valid_flag=no
category=mandatory
get_support=no
set_support=no
get_abstract=no
set_abstract=no
virtual_class_name=null

[vterminal]
type=object
members=vterminal_name,vterminal_description,vterminal_faults,vterminal_state
get_support=yes
set_support=yes

[vterminals]
key=vterminal
type=object
parent_name = vtn_key.vtn_name
parent_name1=empty
parent_name2=empty
item=vterm
get_support=yes
get_abstract=yes

[extra_para]
get_extra_argument=unc::driver::controller* ctr, unc::restjson::ConfFileValues_t conf_values_
extra_parameter=yes
filterlist=no

[para_constructor]
args=parent_name,controller_name,domain_name
data_type=std::string,std::string,std::string

[virtual_method]
get_virtual_method_name=virtual_method
get_virtual_members=controller_name,domain_name
virtual_class_name=VirtualVtermCommand
get_virtual_method=yes

[additional_header]
header=#include<odl_virtual_vterminal.hh>

[get_fill_portmap]
get_fill_portmaps=empty
portmaps=no

[code]
namespace=odcdriver

[class]
name=VtermParser
parameterized_constructor=yes
set_method=create_vterm_request
set_sections=vterminal
get_method=parse_vterm_response
get_sections=vterminals
rest_type=json_object
ipc_key_struct=key_vterm_t
ipc_val_struct=val_vterm_t


