[name]
type=string
key="name"
struct_name=vtn_port
category=mandatory
build_support=no
parse_support=yes

[enabled]
type=int
key="enabled"
struct_name=vtn_port
build_support=no
parse_support=yes

[cost]
type=string
key="cost"
struct_name=vtn_port
build_support=no
parse_support=yes

[id]
type=string
key="id"
struct_name=vtn_port
build_support=no
parse_support=yes

[vtn_port]
type=array
key="vtn-port"
s_array = yes
struct_name=vtn_port
check_bool_set=yes
members=cost,id,name,enabled
get_support=yes
get_abstract=yes

[vtnnode]
type=object
key="vtn-node"
struct_name=vtn_port
members=vtn_port
check_bool_set=yes
get_support=yes
get_abstract=yes

[RESTURL]
type=url_string
value="/restconf"

[SLASH]
type=url_string
value="/"

[VTNINVENTORYURL]
type=url_string
value="vtn-inventory"

[COLON]
type=url_string
value=":"

[OPERATIONURL]
type=url_string
value="operational"

[VTNNODSURL]
type=url_string
value="vtn-nodes"

[VTNNODURL]
type=url_string
value="vtn-node"

[controller_ip]
type=string
get_abstract=yes

[controller_port]
type=string
get_abstract=yes

[switch_id]
type=url_string
get_abstract=yes

[VTN_GETSUPPORT_URL]
type=url_string
url_format=RESTURL,SLASH,OPERATIONURL,SLASH,VTNINVENTORYURL,COLON,VTNNODSURL,SLASH,VTNINVENTORYURL,COLON,VTNNODURL,SLASH,switch_id
interface_members=controller_ip,controller_port

[vtnport_parser]
type=READ
url=VTN_GETSUPPORT_URL
request_type=object
request_members=vtnnode
response_members="vtn-node"
http_success=200

[vtnport_request]
type=READ
url=VTN_GETSUPPORT_URL
request_type=object
interface=switch_id
request_members=vtnnode
response_members="vtn-node"
http_success=200

[READ]
url=VTN_GETSUPPORT_URL

[ROOT]
url_class = vtnport_request
parse_class=vtnport_parser
namespace=odcdriver
struct_type = vtn-port
data=vtn_port
methods=vtnport_request
