[source]
type=string
key="source"
struct_name=vtn_link
build_support =no
parse_support =yes

[destination]
type=string
key="destination"
struct_name=vtn_link
build_support =no
parse_support =yes

[link_id]
type=string
key="link-id"
struct_name=vtn_link
build_support=no
parse_support =yes

[vtn_link]
type=array
key="vtn-link"
is_child=yes
struct_name=vtn_link
check_bool_set=no
members=source,link_id,destination

[cost]
type=string
key="cost"
struct_name=vtn_port
is_child=no
category=mandatory

[id]
type=string
key="id"
is_child=no
struct_name=vtn_port
category=mandatory

[vtn_port]
type=array
key="vtn-port"
is_child=yes
struct_name=vtn_port
check_bool_set=yes
members=cost,id

[vtntopology]
type=object
key="vtn-topology"
is_child=yes
struct_name=vtn_link
check_bool_set=yes
members=vtn_link


[RESTURL]
type=url_string
value="/restconf"

[SLASH]
type=url_string
value="/"

[VTNTOPOLGYURL]
type=url_string
value="vtn-topology"

[COLON]
type=url_string
value=":"

[OPERATIONURL]
type=url_string
value="operational"

[controller_ip]
type=string
get_abstract=yes

[controller_port]
type=string
get_abstract=yes


[VTN_GETSUPPORT_URL]
type=url_string
url_format=RESTURL,SLASH,OPERATIONURL,SLASH,VTNTOPOLGYURL,COLON,VTNTOPOLGYURL
interface_members=controller_ip,controller_port


[vtntopology_parser]
type=READ
request_type=object
request_members=vtntopology
response_members="vtn-topology"
http_success=200

[vtntopology_request]
type=READ
request_type=object
request_members=vtntopology
response_members="vtn-topology"
http_success=200


[READ]
url=VTN_GETSUPPORT_URL


[ROOT]
url_class = vtntopology_request
parse_class=vtntopology_parser
namespace=odcdriver
struct_type = vtn-link
data=vtn_link
methods=vtntopology_request
