# Copyright (c) 2015-2016 NEC Corporation
# All rights reserved.
#
# This program and the accompanying materials are made available under the
# terms of the Eclipse Public License v1.0 which accompanies this
# distribution, and is available at http://www.eclipse.org/legal/epl-v10.html

[SLASH]
type=url_string
value="/"

[VBR_GETSUPPORT_URL]
type=url_string
url_format=GET_BASEURL,SLASH,tenantName

[VBR_COMANSUPPORT_URL]
type=url_string
url_format=BASEURL,SLASH,VBridge,COLON,VBridge-update

[VBR_DELSUPPORT_URL]
type=url_string
url_format=BASEURL,SLASH,VBridge,COLON,VBridge-delete

[GET_BASEURL]
type=url_string
value="/restconf/operational/vtn:vtns/vtn"

[BASEURL]
type=url_string
value="/restconf/operations"

[tenantName]
type=url_string
get_abstract=yes

[VBridge]
type=url_string
value="vtn-vbridge"

[VBridge-update]
type=url_string
value="update-vbridge"

[COLON]
type=url_string
value=":"

[VBridge-delete]
type=url_string
value="remove-vbridge"

[vbr_parser]
type=READ,CU,DEL
request_type=object
parse_request_members=vtn_vbr_conf
build_request_members=ip_vbridges
response_members="vbridges"

[READ]
url=VBR_GETSUPPORT_URL

[CU]
url=VBR_COMANSUPPORT_URL

[DEL]
url=VBR_DELSUPPORT_URL

[vbr_class]
type=READ,CU,DEL
interface=tenantName
request_type=object
request_members=vbridges
response_members="vbridges"

[description]
type=string
key="description"
struct_name=vbridge_config
build_support=no
mandatory=no
parse_support=yes

[vbridge_config]
type=struct
key="vbridge-config"
is_child=yes
check_bool_set=yes
struct_name = vbridge_conf
members= description,valid
build_support=no
mandatory=yes
parse_support=yes

[vbridge_conf]
type=array
key="vbridge"
is_child=yes
check_bool_set=yes
struct_name = vbridge_conf
members= name,vbridge_config,valid
build_support=no
mandatory=yes
parse_support=yes


[vtn_vbr_conf]
type=array
key="vtn"
is_child=yes
check_bool_set=yes
struct_name = vbridge_conf
members=vbridge_conf
build_support=no
mandatory=yes
parse_support=yes

[vbr_input]
type=struct
key="input"
is_child=yes
check_bool_set=yes
struct_name=vbr_input
members=update_mode,operation,tenant_name,bridge_name,ip_description,ageinterval,valid
build_support=yes
mandatory=yes
parse_support=no

[update_mode]
type=string
key="update-mode"
struct_name=vbr_input
mandatory=yes
build_support=yes
parse_support=no

[operation]
type=string
key="operation"
struct_name=vbr_input
mandatory=yes
build_support=yes
parse_support=no

[tenant_name]
type=string
key="tenant-name"
struct_name=vbr_input
mandatory=yes
build_support=yes
parse_support=no

[bridge_name]
type=string
key="bridge-name"
struct_name=vbr_input
mandatory=yes
build_support=yes
parse_support=no

[ip_description]
type=string
key="description"
struct_name=vbr_input
mandatory=no
build_support=yes
parse_support=no

[ageinterval]
type=string
key="age-interval"
struct_name=vbr_input
mandatory=no
build_support=yes
parse_support=no

[valid]
type=bool
key=""
struct_name= vbr_input
mandatory=no
build_support=no
parse_support=no

[ip_vbridge]
type=struct
key="ip_vbridge"
is_child=yes
check_bool_set=yes
struct_name=vbr_input
members= vbr_input,valid
build_support=yes
mandatory=no
parse_support=no

[ip_vbridges]
type=object
key="ip_vbridges"
is_child=yes
check_bool_set=yes
struct_name=ip_vbridge
members=ip_vbridge
build_support=yes
mandatory=no
parse_support=no

[vbridges]
type=object
key="vbridges"
is_child=yes
check_bool_set=yes
struct_name=vbridge_conf
members=vbridge_conf
build_support=no
mandatory=no
parse_support=no

[valid]
type=bool
key=""
struct_name= vbridge_conf
mandatory=no
build_support=no
parse_support=no

[name]
type=string
key="name"
struct_name=vbridge_conf
build_support=no
mandatory=yes
parse_support=yes

[ROOT]
url_class = vbr_class
parse_class=vbr_parser
namespace=odcdriver
struct_type = vtn_vbr_conf,vbr_input
data=vbridge_config,vbridge_conf,vtn_vbr_conf,vbr_input,ip_vbridge
methods= vbr_class
