# Copyright (c) 2016 NEC Corporation
# All rights reserved.
#
# This program and the accompanying materials are made available under the
# terms of the Eclipse Public License v1.0 which accompanies this
# distribution, and is available at http://www.eclipse.org/legal/epl-v10.html

[BASEURL]
type=url_string
value="/restconf/operations"

[GET_BASEURL]
type=url_string
value="/restconf/operational"

[SLASH]
type=url_string
value="/"

[VTN]
type=url_string
value="vtn:vtns/vtn"

[vbridge]
type=url_string
value="vbridge"

[vbridge_input_filter]
type=url_string
value="vbridge-input-filter"

[vtn_flw_filter]
type=url_string
value="vtn-flow-filter"

[set_flow_filter]
type=url_string
value="set-flow-filter"

[remove_flow_filter]
type=url_string
value="remove-flow-filter"

[COLON]
type=url_string
value=":"

[tenantName]
type=url_string
get_abstract=yes

[bridgeName]
type=url_string
get_abstract=yes

[VBRFLOWFILTER_ENTRY_GETSUPPORT_URL]
type=url_string
url_format=GET_BASEURL,SLASH,VTN,SLASH,tenantName,SLASH,vbridge,SLASH,bridgeName

[VBRFLOWFILTER_ENTRY_COMANSUPPORT_URL]
type=url_string
url_format=BASEURL,SLASH,vtn_flw_filter,COLON,set_flow_filter

[VBRFLOWFILTER_ENTRY_DELSUPPORT_URL]
type=url_string
url_format=BASEURL,SLASH,vtn_flw_filter,COLON,remove_flow_filter

[READ]
url=VBRFLOWFILTER_ENTRY_GETSUPPORT_URL

[CU]
url=VBRFLOWFILTER_ENTRY_COMANSUPPORT_URL

[DEL]
url=VBRFLOWFILTER_ENTRY_DELSUPPORT_URL

[condition]
type=string
key="condition"
is_child=yes
mandatory=yes
struct_name=flow_filter
build_support=no
parse_support=yes

[index]
type=int
key="index"
is_child=yes
mandatory=yes
struct_name=flow_filter
build_support=no
parse_support=yes

[vbr_pass_filter]
type=struct
key="vtn-pass-filter"
is_child=yes
struct_name=flow_filter
members=pass_empty,valid
mandatory=no
build_support=no
parse_support=yes

[pass_empty]
type=int
key=" "
mandatory=no
struct_name=vbr_pass_filter
build_support=no
parse_support=yes

[vbr_drop_filter]
type=struct
key="vtn-drop-filter"
is_child=yes
struct_name=flow_filter
members=drop_empty,valid
mandatory=no
build_support=no
parse_support=yes

[drop_empty]
type=int
key=" "
mandatory=no
struct_name=vbr_drop_filter
build_support=no
parse_support=yes

[vbr_redirect_filter]
type=struct
key="vtn-redirect-filter"
is_child=yes
struct_name=flow_filter
mandatory=no
members=redirect_output,vbr_redirect_destination,valid
build_support=no
parse_support=yes

[redirect_output]
type=bool
key="output"
is_child=yes
struct_name=vbr_redirect_filter
mandatory=no
build_support=no
parse_support=yes

[vbr_redirect_destination]
type=struct
key="redirect-destination"
is_child=no
struct_name=vbr_redirect_filter
members=re_tenant_name,re_bridge_name,re_terminal_name,re_interface_name,valid
mandatory=no
build_support=no
parse_support=yes

[re_tenant_name]
type=string
key="tenant-name"
is_child=yes
struct_name=vbr_redirect_destination
mandatory=no
build_support=no
parse_support=yes

[re_bridge_name]
type=string
key="bridge-name"
is_child=yes
struct_name=vbr_redirect_destination
mandatory=no
build_support=no
parse_support=yes

[re_terminal_name]
type=string
key="terminal-name"
is_child=yes
struct_name=vbr_redirect_destination
mandatory=no
build_support=no
parse_support=yes

[re_interface_name]
type=string
key="interface-name"
is_child=yes
struct_name=vbr_redirect_destination
mandatory=no
build_support=no
parse_support=yes

[order]
type=int
key="order"
is_child=yes
struct_name=flow_action
mandatory=yes
build_support=no
parse_support=yes

[vbr_dlsrc]
type=struct
key="vtn-set-dl-src-action"
is_child=yes
struct_name=flow_action
members=dlsrc_address,valid
build_support=no
parse_support=yes

[dlsrc_address]
type=string
key="address"
is_child=yes
struct_name=vbr_dlsrc
mandatory=yes
build_support=no
parse_support=yes

[valid]
type=bool
key=""
mandatory=no
build_support=no
parse_support=no
struct_name=flow_action

[vbr_vlanpcp]
type=struct
key="vtn-set-vlan-pcp-action"
is_child=yes
struct_name=flow_action
members=vlan_pcp,valid
build_support=no
parse_support=yes

[vlan_pcp]
type=int
key="vlan-pcp"
is_child=yes
struct_name=vbr_vlanpcp
mandatory=yes
build_support=no
parse_support=yes

[vbr_dldst]
type=struct
key="vtn-set-dl-dst-action"
is_child=yes
struct_name=flow_action
members=dlsdt_address,valid
build_support=no
parse_support=yes

[dlsdt_address]
type=string
key="address"
is_child=yes
struct_name=vbr_dldst
mandatory=yes
build_support=no
parse_support=yes

[vbr_inet4src]
type=struct
key="vtn-set-inet-src-action"
is_child=yes
struct_name=flow_action
members=inet4src_address,valid
build_support=no
parse_support=yes

[inet4src_address]
type=string
key="address"
is_child=yes
struct_name=vbr_inet4src
build_support=no
parse_support=no

[vbr_inet4dst]
type=struct
key="vtn-set-inet-dst-action"
is_child=yes
struct_name=flow_action
members=inet4dst_address,valid
build_support=no
parse_support=yes

[inet4dst_address]
type=string
key="address"
is_child=yes
struct_name=vbr_inet4dst
build_support=no
parse_support=no

[vbr_dscp]
type=struct
key="vtn-set-inet-dscp-action"
is_child=yes
struct_name=flow_action
members=dscp_value,valid
build_support=no
parse_support=yes

[dscp_value]
type=int
key="dscp"
is_child=yes
struct_name=vbr_dscp
mandatory=yes
build_support=no
parse_support=yes

[vbr_tpsrc]
type=struct
key="vtn-set-port-src-action"
is_child=yes
struct_name=flow_action
members=port_value,valid
build_support=no
parse_support=no

[port_value]
type=int
key="port"
is_child=yes
struct_name=flow_action
build_support=no
parse_support=no

[vbr_tpdst]
type=struct
key="vtn-set-port-dst-action"
is_child=yes
struct_name=flow_action
members=tpdst_port,valid
build_support=no
parse_support=no

[tpdst_port]
type=int
key="port"
is_child=yes
struct_name=flow_action
build_support=no
parse_support=no

[vbr_icmptype]
type=struct
key="vtn-set-icmp-type-action"
is_child=yes
struct_name=flow_action
members=icmp_type,valid
build_support=no
parse_support=no

[icmp_type]
type=int
key="type"
is_child=yes
struct_name=flow_action
build_support=no
parse_support=no

[vbr_icmpcode]
type=struct
key="vtn-set-icmp-code-action"
is_child=yes
struct_name=flow_action
members=icmp_code,valid
build_support=no
parse_support=no

[icmp_code]
type=int
key="code"
is_child=yes
struct_name=flow_action
build_support=no
parse_support=no

[flow_action]
type=array
key="vtn-flow-action"
is_child=yes
struct_name=flow_action
members=order,vbr_dlsrc,vbr_vlanpcp,vbr_dldst,vbr_inet4src,vbr_inet4dst,vbr_dscp,vbr_tpsrc,vbr_tpdst,vbr_icmptype,vbr_icmpcode,valid
check_bool_set=yes
build_support=no
parse_support=yes

[flow_filter]
type=array
key="vtn-flow-filter"
is_child=yes
struct_name=flow_filter
mandatory=yes
members=condition,index,vbr_pass_filter,vbr_drop_filter,vbr_redirect_filter,flow_action,valid
check_bool_set=yes
build_support=no
parse_support=yes

[vbr_flowfilter]
type=struct
key="vbridge-input-filter"
is_child=no
check_bool_set=no
struct_name=flow_filter
members=flow_filter,valid
build_support=no
parse_support=yes

[vbridge_filter]
type=array
key="vbridge"
is_child=no
check_bool_set=yes
struct_name=flow_filter
members=vbr_flowfilter
build_support=no
parse_support=yes

[pa_vbr_flowfilters]
type=struct
key="vbridge-flow-filter"
is_child=yes
check_bool_set=yes
struct_name=vbr_flowfilter
members=flow_filter
build_support=no
parse_support=no

[vbrflowfilter_parser]
type = READ,CU,DEL
request_type = object
parse_request_members = vbridge_filter
build_request_members = pa_vbr_flowfilters
response_members = "ip_vbr_flowfilters"

[vbrflowfilter_class]
type = READ,CU,DEL
interface = tenantName,bridgeName
request_type = object
request_members = pa_vbr_flowfilters
response_members = "ip_vbr_flowfilters"

[ROOT]
url_class = vbrflowfilter_class
parse_class = vbrflowfilter_parser
namespace = odcdriver
struct_type = flow_filter
data = vbr_redirect_destination,vbr_redirect_filter,vbr_drop_filter,vbr_pass_filter,vbr_dlsrc,vbr_vlanpcp,vbr_dldst,vbr_inet4src,vbr_inet4dst,vbr_dscp,vbr_tpsrc,vbr_tpdst,vbr_icmptype,vbr_icmpcode,flow_action,flow_filter,vbr_flowfilter,vbridge_filter
methods = vbrflowfilter_class
