[name]
type=string
key="name"
struct_name=vbr_if_conf
build_support=no
parse_support=yes

[enabled]
type=bool
key="enabled"
struct_name=vbr_vinterface_config
build_support=no
parse_support=yes

[description]
type=string
key="description"
struct_name=vbr_vinterface_config
build_support=no
parse_support=yes

[valid]
type=bool
key=""
struct_name= vbr_if_conf
mandatory=no
build_support=no
parse_support=no

[valid]
type=bool
key=""
struct_name=ip_vbridge_config
mandatory=no
build_support=no
parse_support=no

[vbr_vinterface_config]
type=struct
key="vinterface-config"
struct_name=vbr_if_conf
check_bool_set=no
is_child=yes
members=enabled,description,valid
build_support=no
parse_support=yes

[vbridge_config]
type=object
key="vbridge-config"
struct_name=vbr_if_conf
is_child=yes
check_bool_set=yes
members=vbr_if
build_support=no
parse_support=no

[vbr_if_conf]
type=array
key="vinterface"
is_child=yes
check_bool_set=yes
struct_name = vbr_if_conf
members=name,vbr_vinterface_config,valid
build_support=no
parse_support=yes

[vbridge_if_conf]
type=array
key="vbridge"
is_child=yes
check_bool_set=yes
struct_name = vbr_if_conf
members=vbr_if_conf
build_support=no
parse_support=yes

[ip_vbridge_config]
type=struct
key="ip_vbridge_config"
is_child=yes
check_bool_set=yes
struct_name=ip_vbridge_config
members=input_vbrif,valid
build_support=yes
parse_support=no

[ip_vbridge_configs]
type=object
key="ip_vbridge_configs"
is_child=yes
check_bool_set=yes
struct_name=ip_vbridge_config
members= ip_vbridge_config
build_support=yes
parse_support=no

[REST_URL]
type=url_string
value="/restconf/operations"

[GET_REST_URL]
type=url_string
value="/restconf/operational"

[VTN]
type=url_string
value="vtn:vtns/vtn"

[tenantName]
type=url_string
get_abstract=yes

[SLASH]
type=url_string
value="/"

[COLON]
type=url_string
value=":"

[VBR]
type=url_string
value="vbridge"

[bridgeName]
type=url_string
get_abstract=yes

[VTN_Vinterface]
type=url_string
value="vtn-vinterface"

[Update_vinterface]
type=url_string
value="update-vinterface"

[Remove-vinterface]
type=url_string
value="remove-vinterface"

[VBR_IF_GETURL]
type=url_string
url_format=GET_REST_URL,SLASH,VTN,SLASH,tenantName,SLASH,VBR,SLASH,bridgeName

[VBR_IF_COMMONURL]
type=url_string
url_format=REST_URL,SLASH,VTN_Vinterface,COLON,Update_vinterface

[VBR_IF_DELETEURL]
type=url_string
url_format=REST_URL,SLASH,VTN_Vinterface,COLON,Remove-vinterface

[vbrif_class]
type=READ,CU,DEL
request_type=object
interface=tenantName,bridgeName
request_members=vbridge_config
response_members="vbridge-config"
http_success=200

[vbrif_parser]
type=READ,CU,DEL
request_type=object
parse_request_members=vbridge_if_conf
build_request_members=ip_vbridge_configs
request_members=vbridge_config
response_members="vbridge-config"
http_success=200

[input_vbrif]
type=struct
key="input"
is_child=yes
check_bool_set=yes
struct_name=vbrif_input
members=update_mode,operation,tenant_name,bridge_name,input_description,input_enabled,interface_name,valid
build_support=yes
parse_support=no

[update_mode]
type=string
key="update-mode"
struct_name=input_vbrif
mandatory=yes
build_support=yes
parse_support=no

[operation]
type=string
key="operation"
struct_name=input_vbrif
mandatory=yes
build_support=yes
parse_support=no

[tenant_name]
type=string
key="tenant-name"
struct_name=input_vbrif
mandatory=yes
build_support=yes
parse_support=no

[bridge_name]
type=string
key="bridge-name"
struct_name=input_vbrif
mandatory=yes
build_support=yes
parse_support=no

[input_description]
type=string
key="description"
struct_name=input_vbrif
mandatory=yes
build_support=yes
parse_support=no

[input_enabled]
type=bool
key="enabled"
struct_name=input_vbrif
mandatory=no
build_support=yes
parse_support=no

[interface_name]
type=string
key="interface-name"
struct_name=input_vbrif
mandatory=yes
build_support=yes
parse_support=no

[READ]
url=VBR_IF_GETURL

[CU]
url=VBR_IF_COMMONURL

[DEL]
url=VBR_IF_DELETEURL

[ROOT]
url_class=vbrif_class
parse_class=vbrif_parser
namespace=odcdriver
struct_type=vbridge_if_conf,ip_vbridge_config
data=vbr_vinterface_config,vbr_if_conf,vbridge_if_conf,input_vbrif,ip_vbridge_config
methods=vbrif_class
