# Copyright (c) 2015-2016 NEC Corporation
# All rights reserved.
#
# This program and the accompanying materials are made available under the
# terms of the Eclipse Public License v1.0 which accompanies this
# distribution, and is available at http://www.eclipse.org/legal/epl-v10.html

[SLASH]
type=url_string
value="/"

[BASE_URL]
type=url_string
value="/restconf/operations"

[GET_REST_URL]
type=url_string
value="/restconf/operational"


[VLAN_GETSUPPORT_URL]
type=url_string
url_format=GET_REST_URL,SLASH,VTNS,SLASH,tenantname,SLASH,VBRIDGES,SLASH,bridgename

[VLAN_COMANSUPPORT_URL]
type=url_string
url_format=BASEURL,SLASH,VTN,COLON,ADD_VLANMAPS

[VLAN_DELSUPPORT_URL]
type=url_string
url_format=BASEURL,SLASH,VTN,COLON,DEL_VLANMAPS


[BASEURL]
type=url_string
value="/restconf/operations"

[VTNS]
type=url_string
value="vtn:vtns/vtn"

[COLON]
type=url_string
value=":"

[VTN]
type=url_string
value="vtn-vlan-map"

[tenantname]
type=url_string
get_abstract=yes

[VBRIDGES]
type=url_string
value="vbridge"

[bridgename]
type=url_string
get_abstract=yes

[ADD_VLANMAPS]
type=url_string
value="add-vlan-map"

[DEL_VLANMAPS]
type=url_string
value="remove-vlan-map"

[valid]
type=bool
key=""
struct_name= vlan_conf
mandatory=no
build_support=no
parse_support=no

[vlan_parser]
type=READ,CU,DEL
request_type=object
parse_request_members=vbr_vlan_conf
build_request_members=ip_vlan_configs
response_members="vlan_config"
http_success=200


[READ]
url=VLAN_GETSUPPORT_URL

[CU]
url=VLAN_COMANSUPPORT_URL

[DEL]
url=VLAN_DELSUPPORT_URL


[vlan_class]
type=READ,CU,DEL
interface=tenantname,bridgename
request_type=object
request_members=vlan_config
response_members="vlan_config"
http_success=201

[map_id]
type=string
key="map-id"
struct_name=vlan_conf
build_support=no
mandatory=yes
parse_support=yes

[vlanid]
type=int
key="vlan-id"
struct_name=vlanmap_config
build_support=no
mandatory=yes
parse_support=yes

[vlanmap_config]
type=struct
key="vlan-map-config"
is_child=yes
check_bool_set=yes
struct_name = vlan_conf
members=vlanid,valid
build_support = no
mandatory=yes
parse_support = yes

[vlan_conf]
type=array
key="vlan-map"
is_child=yes
check_bool_set=yes
struct_name=vlan_conf
members=map_id,vlanmap_config,valid
build_support=no
mandatory=yes
parse_support=yes

[vbr_vlan_conf]
type=arrray
key="vbridge"
is_child=yes
check_bool_set=yes
struct_name=vlan_conf
members=vlan_conf
build_support=no
mandatory=yes
parse_support=yes

[vlan_config]
type=object
key=""
is_child=yes
check_bool_set=yes
struct_name=vlan_conf
members=vlan_conf
build_support=no
mandatory=yes
parse_support=no

[tenant_name]
type=string
key="tenant-name"
struct_name=input_vlan
mandatory=yes
build_support=yes
parse_support=no

[bridge_name]
type=string
key="bridge-name"
struct_name=input_vlan
mandatory=yes
build_support=yes
parse_support=no

[vlan_id]
type=string
key="vlan-id"
struct_name= input_vlan
build_support=yes
parse_support=no
mandatory = yes

[node]
type=string
key="node"
struct_name = input_vlan
build_support=yes
parse_support=no
mandatory = no

[valid]
type=bool
key=""
struct_name= ip_vlan_config
mandatory=no
build_support=no
parse_support=no

[input_vlan]
type=struct
key="input"
is_child=yes
check_bool_set=no
struct_name=ip_vlan_config
members=tenant_name,bridge_name,node,vlan_id,valid
build_support=yes
mandatory=yes
parse_support=no

[ip_vlan_config]
type=struct
key="ip_vlan_config"
is_child=yes
check_bool_set=yes
struct_name=ip_vlan_config
members=input_vlan,valid
mandatory=yes
build_support=yes
parse_support=no

[ip_vlan_configs]
type=object
key="ip_vlan_configs"
is_child=yes
check_bool_set=yes
struct_name=ip_vlan_config
members=ip_vlan_config
mandatory=yes
build_support=yes
parse_support=no

[ROOT]
url_class = vlan_class
parse_class=vlan_parser
namespace=odcdriver
struct_type = vbr_vlan_conf,ip_vlan_config
data=vlanmap_config,vlan_conf,vbr_vlan_conf,input_vlan,ip_vlan_config
methods= vlan_class
