# Copyright (c) 2016 NEC Corporation
# All rights reserved.
#
# This program and the accompanying materials are made available under the
# terms of the Eclipse Public License v1.0 which accompanies this
# distribution, and is available at http://www.eclipse.org/legal/epl-v10.html

[BASEURL]
type=url_string
value="/restconf/operations"

[GET_BASEURL]
type=url_string
value="/restconf/operational"

[SLASH]
type=url_string
value="/"

[VTN]
type=url_string
value="vtn:vtns/vtn"

[vbridge]
type=url_string
value="vbridge"

[vtn_flw_filter]
type=url_string
value="vtn-flow-filter"

[set_flow_filter]
type=url_string
value="set-flow-filter"

[remove_flow_filter]
type=url_string
value="remove-flow-filter"

[COLON]
type=url_string
value=":"

[tenantName]
type=url_string
get_abstract=yes

[termName]
type=url_string
get_abstract=yes

[ifName]
type=url_string
get_abstract=yes

[VTERMIF_FLOWFILTER_ENTRY_GETSUPPORT_URL]
type=url_string
url_format=GET_BASEURL,SLASH,VTN,SLASH,tenantName,SLASH,termName,SLASH,ifName

[VTERMIF_FLOWFILTER_ENTRY_COMANSUPPORT_URL]
type=url_string
url_format=BASEURL,SLASH,vtn_flw_filter,COLON,set_flow_filter

[VTERMIF_FLOWFILTER_ENTRY_DELSUPPORT_URL]
type=url_string
url_format=BASEURL,SLASH,vtn_flw_filter,COLON,remove_flow_filter

[READ]
url=VTERMIF_FLOWFILTER_ENTRY_GETSUPPORT_URL

[CU]
url=VTERMIF_FLOWFILTER_ENTRY_COMANSUPPORT_URL

[DEL]
url=VTERMIF_FLOWFILTER_ENTRY_DELSUPPORT_URL

[input_vtermif_flow_filter]
type=struct
key="input"
is_child=yes
check_bool_set=yes
struct_name=ip_vterm_if_flowfilter
members=output,tenant_name,terminal_name,interface_name,vtermin_flow_filter,valid
build_support=yes
parse_support=no

[output]
type=bool
key="output"
is_child=yes
check_bool_set=yes
mandatory=yes
struct_name=input_vtermif_flow_filter
build_support=yes
parse_support=no

[tenant_name]
type=string
key="tenant-name"
is_child=yes
check_bool_set=yes
mandatory=yes
struct_name=input_vtermif_flow_filter
build_support=yes
parse_support=no

[terminal_name]
type=string
key="terminal-name"
is_child=yes
check_bool_set=yes
mandatory=yes
struct_name=input_vtermif_flow_filter
build_support=yes
parse_support=no

[interface_name]
type=string
key="interface-name"
is_child=yes
check_bool_set=yes
mandatory=yes
struct_name=input_vtermif_flow_filter
build_support=yes
parse_support=no

[vtermin_flow_filter]
type=array
key="vtn-flow-filter"
is_child=yes
check_bool_set=yes
struct_name=vtermin_flow_filter
mandatory=yes
members=condition,index,vtermin_pass_filter,vtermin_drop_filter,vtermin_redirect_filter,vtermin_flow_action,valid
build_support=yes
parse_support=no

[condition]
type=string
key="condition"
is_child=yes
mandatory=yes
struct_name=vtermin_flow_filter
build_support=yes
parse_support=no

[index]
type=int
key="index"
is_child=yes
mandatory=yes
struct_name=vtermin_flow_filter
build_support=yes
parse_support=no

[vtermin_pass_filter]
type=struct
key="vtn-pass-filter"
is_child=yes
mandatory=no
struct_name=vtermin_flow_filter
members=pass_empty,valid
build_support=yes
parse_support=no

[pass_empty]
type=string
key=""
mandatory=no
struct_name=vtermin_flow_filter
build_support=no
parse_support=no

[vtermin_drop_filter]
type=struct
key="vtn-drop-filter"
is_child=yes
mandatory=no
struct_name=vtermin_flow_filter
members=drop_empty,valid
build_support=yes
parse_support=no

[drop_empty]
type=string
key=""
mandatory=no
struct_name=vtermin_flow_filter
build_support=no
parse_support=no

[vtermin_redirect_filter]
type=struct
key="vtn-redirect-filter"
is_child=yes
struct_name=vtermin_flow_filter
mandatory=no
members=redirect_output,vtermin_redirect_destination,valid
build_support=yes
parse_support=no

[redirect_output]
type=bool
key="output"
is_child=yes
struct_name=vtermin_redirect_filter
mandatory=no
build_support=yes
parse_support=no

[vtermin_redirect_destination]
type=struct
key="redirect-destination"
is_child=yes
struct_name=vtermin_redirect_filter
members=vtermin_tenant_name,vtermin_bridge_name,vtermin_terminal_name,vtermin_interface_name,valid
mandatory=no
build_support=yes
parse_support=no

[vtermin_tenant_name]
type=string
key="tenant-name"
is_child=yes
mandatory=no
struct_name=vtermin_redirect_destination
build_support=yes
parse_support=no

[vtermin_bridge_name]
type=string
key="bridge-name"
is_child=yes
mandatory=no
struct_name=vtermin_redirect_destination
build_support=yes
parse_support=no

[vtermin_terminal_name]
type=string
key="terminal-name"
is_child=yes
struct_name=vtermin_redirect_destination
mandatory=no
build_support=yes
parse_support=no

[vtermin_interface_name]
type=string
key="interface-name"
is_child=yes
struct_name=vtermin_redirect_destination
mandatory=yes
build_support=yes
parse_support=no

[vtermin_flow_action]
type=array
key="vtn-flow-action"
is_child=yes
check_bool_set=no
struct_name=vtermin_flow_action
mandatory=yes
members=order,vtermin_dlsrc,vtermin_vlanpcp,vtermin_dldst,vtermin_inet4src,vtermin_inet4dst,vtermin_dscp,vtermin_tpsrc,vtermin_tpdst,vtermin_icmptype,vtermin_icmpcode,valid
build_support=yes
parse_support=no

[order]
type=int
key="order"
is_child=yes
struct_name=vtermin_flow_action
mandatory=yes
build_support=yes
parse_support=no

[vtermin_dlsrc]
type=struct
key="vtn-set-dl-src-action"
is_child=yes
struct_name=vtermin_flow_action
members=dlsrc_address,valid
build_support=yes
parse_support=no

[dlsrc_address]
type=string
key="address"
is_child=yes
struct_name=vtermin_dlsrc
mandatory=yes
build_support=yes
parse_support=no

[valid]
type=bool
key=""
mandatory=no
build_support=no
parse_support=no

[vtermin_vlanpcp]
type=struct
key="vtn-set-vlan-pcp-action"
is_child=yes
struct_name=vtermin_flow_action
members=vlan_pcp,valid
mandatory=no
build_support=yes
parse_support=no

[vlan_pcp]
type=int
key="vlan-pcp"
is_child=yes
mandatory=yes
struct_name=vtermin_vlanpcp
build_support=yes
parse_support=no

[vtermin_dldst]
type=struct
key="vtn-set-dl-dst-action"
is_child=yes
mandatory=no
struct_name=vtermin_flow_action
members=dldst_address,valid
mandatory=no
build_support=yes
parse_support=no

[dldst_address]
type=string
key="address"
is_child=yes
mandatory=no
struct_name=vtermin_dldst
build_support=yes
parse_support=no

[vtermin_inet4src]
type=struct
key="vtn-set-inet-src-action"
is_child=yes
mandatory=no
struct_name=vtermin_flow_action
members=inet4src_address,valid
build_support=yes
parse_support=no

[inet4src_address]
type=string
key="address"
is_child=yes
mandatory=no
struct_name=vtermin_inet4src
build_support=no
parse_support=no

[vtermin_inet4dst]
type=struct
key="vtn-set-inet-dst-action"
is_child=yes
mandatory=no
struct_name=vtermin_flow_action
members=inet4dst_address,valid
build_support=yes
parse_support=no

[inet4dst_address]
type=string
key="address"
is_child=yes
mandatory=no
struct_name=vtermin_inet4dst
build_support=no
parse_support=no

[vtermin_dscp]
type=struct
key="vtn-set-inet-dscp-action"
is_child=yes
mandatory=no
struct_name=vtermin_flow_action
members=dscp_value,valid
build_support=yes
parse_support=no

[dscp_value]
type=int
key="dscp"
is_child=yes
mandatory=no
struct_name=vtermin_dscp
build_support=yes
parse_support=no

[vtermin_tpsrc]
type=struct
key="vtn-set-port-src-action"
is_child=yes
mandatory=no
struct_name=vtermin_flow_action
members=port_value,valid
build_support=no
parse_support=no

[port_value]
type=int
key="port"
is_child=yes
mandatory=no
struct_name=vtermin_tpsrc
build_support=no
parse_support=no

[vtermin_tpdst]
type=struct
key="vtn-set-port-dst-action"
is_child=yes
mandatory=no
struct_name=vtermin_flow_action
members=tpdst_port
build_support=no
parse_support=no

[tpdst_port]
type=int
key="port"
is_child=yes
struct_name=vtermin_tpdst
build_support=no
parse_support=no

[vtermin_icmptype]
type=struct
key="vtn-set-icmp-type-action"
is_child=yes
struct_name=vtermin_flow_action
mandatory=no
members=icmp_type
build_support=no
parse_support=no

[icmp_type]
type=int
key="vtn-set-icmp-type-action"
is_child=yes
struct_name=vtermin_icmptype
mandatory=no
build_support=no
parse_support=no

[vtermin_icmpcode]
type=struct
key="vtn-set-icmp-code-action"
is_child=yes
struct_name=vtermin_flow_action
mandatory=no
members=icmp_code,valid
build_support=no
parse_support=no

[icmp_code]
type=int
key="code"
is_child=yes
struct_name=vtermin_icmpcode
mandatory=no
build_support=no
parse_support=no

[ip_vterm_if_flowfilter]
type=struct
key="ip_vterm_if_flowfilter"
is_child=yes
check_bool_set=yes
struct_name=ip_vterm_if_flowfilter
members=input_vtermif_flow_filter,valid
build_support=yes
parse_support=no

[ip_vterm_if_flowfilters]
type=object
key="ip_vterm_if_flowfilters"
is_child=yes
check_bool_set=yes
struct_name=ip_vterm_if_flowfilter
members=ip_vterm_if_flowfilter
build_support=yes
parse_support=no

[vtermint_flowfilters]
type=object
key="ip_vterm_flowfilters"
is_child=yes
check_bool_set=yes
struct_name=ip_vterm_if_flowfilter
members=vtermint_flowfilters
build_support=no
parse_support=no

[vtermif_flowfilter_entry_parser]
type=READ,CU,DEL
request_type=object
parse_request_members=vtermint_flowfilters
build_request_members=ip_vterm_if_flowfilters
response_members="ip_vterm_if_flowfilters"

[vtermif_flowfilter_entry_class]
type=READ,CU,DEL
interface = tenantName,termName,ifName
request_type = object
request_members = ip_vterm_if_flowfilters
response_members = "ip_vterm_if_flowfilters"

[ROOT]
url_class = vtermif_flowfilter_entry_class
parse_class = vtermif_flowfilter_entry_parser
namespace = odcdriver
struct_type = vtermin_flow_filter, ip_vterm_if_flowfilter
data = vtermin_dlsrc,vtermin_vlanpcp,vtermin_dldst,vtermin_inet4src,vtermin_inet4dst,vtermin_dscp,vtermin_tpsrc,vtermin_tpdst,vtermin_icmptype,vtermin_icmpcode,vtermin_redirect_destination,vtermin_pass_filter,vtermin_drop_filter,vtermin_redirect_filter,vtermin_flow_action,vtermin_flow_filter,input_vtermif_flow_filter,ip_vterm_if_flowfilter
methods = vtermif_flowfilter_entry_class
