[BASEURL]
type=url_string
value="/restconf/operations"

[GET_BASEURL]
type=url_string
value="/restconf/operational"

[SLASH]
type=url_string
value="/"

[COLON]
type=url_string
value=":"

[vtn-vinterface]
type=url_string
value="vtn-vinterface"

[update-vinterface]
type=url_string
value="update-vinterface"

[remove-vinterface]
type=url_string
value="remove-vinterface"

[VTERM]
type=url_string
value="vtn:vtns/vtn"

[tenantname]
type=url_string
get_abstract=yes

[termname]
type=url_string
get_abstract=yes

[interfaces]
type=url_string
value="vinterface"

[vterminals]
type=url_string
value="vterminal"

[ifname]
type=url_string
get_abstract=yes

[name]
type=string
key ="name"
struct_name=vterm_if_conf
build_support=no
parse_support=yes

[description]
type=string
key="description"
struct_name=vterm_vinterface_config
build_support=yes
parse_support=yes

[enabled]
type=bool
key="enabled"
struct_name=vterm_vinterface_config
build_support=yes
parse_support=yes

[VTERM_GETSUPPORT_URL]
type=url_string
url_format=GET_BASEURL,SLASH,VTERM,SLASH,tenantname,SLASH,vterminals,SLASH,termname

[VTERM_COMANSUPPORT_URL]
type=url_string
url_format=BASEURL,SLASH,vtn-vinterface,COLON,update-vinterface

[VTERM_DELSUPPORT_URL]
type=url_string
url_format=BASEURL,SLASH,vtn-vinterface,COLON,remove-vinterface

[input_vtermif]
type=struct
key="input"
is_child=yes
check_bool_set=yes
struct_name=vtermif_input
members=update_mode,operation,vtermif_description,vtermif_enabled,tenant_name,terminal_name,interface_name,valid
build_support=yes
parse_support=no

[update_mode]
type=string
key="update-mode"
struct_name=input_vtermif
mandatory=yes
build_support=yes
parse_support=no

[operation]
type=string
key="operation"
struct_name=input_vtermif
mandatory=yes
build_support=yes
parse_support=no

[vtermif_description]
type=string
key="description"
struct_name=input_vtermif
mandatory=yes
build_support=yes
parse_support=no

[vtermif_enabled]
type=bool
key="enabled"
struct_name=input_vtermif
mandatory=no
build_support=yes
parse_support=no

[tenant_name]
type=string
key="tenant-name"
struct_name=input_vtermif
mandatory=yes
build_support=yes
parse_support=no

[terminal_name]
type=string
key="terminal-name"
struct_name=input_vtermif
mandatory=yes
build_support=yes
parse_support=no

[interface_name]
type=string
key="interface-name"
struct_name=input_vtermif
mandatory=yes
build_support=yes
parse_support=no

[vtermif_odl]
type=READ,CU,DEL
request_type=object
parse_request_members=vterminal_if_conf
build_request_members=ip_vterminal_configs
request_members=vterminal_config
response_members="vterminal-config"

[READ]
url=VTERM_GETSUPPORT_URL

[CU]
url=VTERM_COMANSUPPORT_URL

[DEL]
url=VTERM_DELSUPPORT_URL

[vtermif_class]
type=READ,CU,DEL
interface=tenantName,termName
request_type=object
request_members=vterminal_config
response_members="vterminal-config"

[valid]
type=bool
key=""
struct_name= vterm_if_conf
mandatory=no
build_support=no
parse_support=no

[valid]
type=bool
key=""
struct_name=ip_vterminal_config
mandatory=no
build_support=no
parse_suport=no

[vterminal_if_conf]
type=array
key="vterminal"
is_child=yes
check_bool_set=yes
struct_name=vterm_if_conf
members=vterm_if_conf
build_support=no
parse_support=yes

[vterm_if_conf]
type=array
key="vinterface"
is_child=yes
check_bool_set=yes
struct_name=vterm_if_conf
members=name,vterm_vinterface_config,valid
build_support=no
parse_support=yes

[vterminal_config]
type=object
key="vterminal-config"
is_child=yes
check_bool_set=yes
struct_name = vterm_if_conf
members=vterminal_if
build_support=no
parse_support=no

[vterm_vinterface_config]
type=struct
key="vinterface-config"
struct_name=vterm_if_conf
check_bool_set=no
is_child=yes
members=enabled,description,valid
build_support=no
parse_support=yes

[ip_vterminal_config]
type=struct
key="ip_vterminal_config"
is_child=yes
check_bool_set=yes
struct_name=ip_vterminal_config
members=input_vtermif,valid
build_support=yes
parse_support=no

[ip_vterminal_configs]
type=object
key="ip_vterminal_configs"
is_child=yes
check_bool_set=yes
struct_name=ip_vterminal_config
members=ip_vterminal_config
build_support=yes
parse_support=no

[ROOT]
url_class = vtermif_class
parse_class=vtermif_odl
namespace=odcdriver
struct_type = vterminal_if_conf,ip_vterminal_config
data=vterm_vinterface_config,vterm_if_conf,vterminal_if_conf,input_vtermif,ip_vterminal_config
methods= vtermif_class
