# Copyright (c) 2016 NEC Corporation
# All rights reserved.
#
# This program and the accompanying materials are made available under the
# terms of the Eclipse Public License v1.0 which accompanies this
# distribution, and is available at http://www.eclipse.org/legal/epl-v10.html

[BASEURL]
type=url_string
value="/restconf/operations"

[GET_BASEURL]
type=url_string
value="/restconf/operational"

[SLASH]
type=url_string
value="/"

[VTN]
type=url_string
value="vtn:vtns/vtn"

[vbridge]
type=url_string
value="vbridge"

[vinterface_input_filter]
type=url_string
value="vinterface-input-filter"

[vtn_flw_filter]
type=url_string
value="vtn-flow-filter"

[set_flow_filter]
type=url_string
value="set-flow-filter"

[remove_flow_filter]
type=url_string
value="remove-flow-filter"

[COLON]
type=url_string
value=":"

[tenantName]
type=url_string
get_abstract=yes

[termName]
type=url_string
get_abstract=yes

[ifName]
type=url_string
get_abstract=yes

[VTERMIF_FLOWFILTER_ENTRY_GETSUPPORT_URL]
type=url_string
url_format=GET_BASEURL,SLASH,VTN,SLASH,tenantName,SLASH,termName,SLASH,ifName

[VTERMIF_FLOWFILTER_ENTRY_COMANSUPPORT_URL]
type=url_string
url_format=BASEURL,SLASH,vtn_flw_filter,COLON,set_flow_filter

[VTERMIF_FLOWFILTER_ENTRY_DELSUPPORT_URL]
type=url_string
url_format=BASEURL,SLASH,vtn_flw_filter,COLON,remove_flow_filter

[READ]
url=VTERMIF_FLOWFILTER_ENTRY_GETSUPPORT_URL

[CU]
url=VTERMIF_FLOWFILTER_ENTRY_COMANSUPPORT_URL

[DEL]
url=VTERMIF_FLOWFILTER_ENTRY_DELSUPPORT_URL

[condition]
type=string
key="condition"
is_child=yes
mandatory=yes
struct_name=vtermif_flow_filter
build_support=no
parse_support=yes

[index]
type=int
key="index"
is_child=yes
mandatory=yes
struct_name=vtermif_flow_filter
build_support=no
parse_support=yes

[vtermif_vtn_pass_filter]
type=struct
key="vtn-pass-filter"
is_child=yes
struct_name=vtermif_flow_filter
mandatory=no
members=pass_empty,valid
build_support=no
parse_support=yes

[pass_empty]
type=int
key=" "
mandatory=no
struct_name=vtermif_vtn_pass_filter
build_support=no
parse_support=yes

[vtermif_vtn_drop_filter]
type=struct
key="vtn-drop-filter"
is_child=yes
struct_name=vtermif_flow_filter
members=drop_empty,valid
mandatory=no
build_support=no
parse_support=yes

[drop_empty]
type=int
key=" "
mandatory=no
struct_name=vtermif_vtn_drop_filter
build_support=no
parse_support=yes

[vtermif_vtn_redirect_filter]
type=struct
key="vtn-redirect-filter"
is_child=yes
struct_name=vtermif_flow_filter
mandatory=no
members=redirect_output,vtermif_redirect_destination,valid
build_support=no
parse_support=yes

[redirect_output]
type=bool
key="output"
is_child=yes
struct_name=vtermif_vtn_redirect_filter
mandatory=no
build_support=no
parse_support=yes

[vtermif_redirect_destination]
type=struct
key="redirect-destination"
is_child=yes
struct_name=vtermif_vtn_redirect_filter
members=vtermif_tenant_name,vtermif_bridge_name,vtermif_terminal_name,vtermif_interface_name,valid
mandatory=no
build_support=no
parse_support=yes

[vtermif_tenant_name]
type=string
key="tenant-name"
is_child=yes
struct_name=vtermif_redirect_destination
mandatory=no
build_support=no
parse_support=yes

[vtermif_bridge_name]
type=string
key="bridge-name"
is_child=yes
mandatory=no
struct_name=vtermif_redirect_destination
build_support=no
parse_support=yes

[vtermif_terminal_name]
type=string
key="terminal-name"
is_child=yes
mandatory=no
struct_name=vtermif_redirect_destination
build_support=no
parse_support=yes

[vtermif_interface_name]
type=string
key="interface-name"
is_child=yes
mandatory=no
struct_name=vtermif_redirect_destination
build_support=no
parse_support=yes

[order]
type=int
key="order"
is_child=yes
struct_name=vtermif_flow_action
mandatory=yes
build_support=no
parse_support=yes

[vtermif_dlsrc]
type=struct
key="vtn-set-dl-src-action"
is_child=yes
struct_name=vtermif_flow_action
members=dlsrc_address,valid
build_support=no
parse_support=yes

[dlsrc_address]
type=string
key="address"
is_child=yes
mandatory=yes
struct_name=vtermif_dlsrc
build_support=no
parse_support=yes

[valid]
type=bool
key=""
mandatory=no
struct_name=vtermif_flow_action
build_support=no
parse_support=no

[vtermif_vlanpcp]
type=struct
key="vtn-set-vlan-pcp-action"
is_child=yes
struct_name=vtermif_flow_action
members=vlan_pcp,valid
build_support=no
parse_support=yes

[vlan_pcp]
type=int
key="vlan-pcp"
is_child=yes
struct_name=vtermif_vlanpcp
mandatory=yes
build_support=no
parse_support=yes

[vtermif_dldst]
type=struct
key="vtn-set-dl-dst-action"
is_child=yes
struct_name=vtermif_flow_action
members=dldst_address,valid
build_support=no
parse_support=yes

[dldst_address]
type=string
key="address"
is_child=yes
struct_name=vtermif_dldst
mandatory=yes
build_support=no
parse_support=yes

[vtermif_inet4src]
type=struct
key="vtn-set-inet-src-action"
is_child=yes
struct_name=vtermif_flow_action
members=inet4src_address,valid
build_support=no
parse_support=yes

[inet4src_address]
type=string
key="address"
is_child=yes
struct_name=vtermif_inet4src
members=inet4dst_address
build_support=no
parse_support=no

[vtermif_inet4dst]
type=struct
key="vtn-set-inet-dst-action"
is_child=yes
struct_name=vtermif_flow_action
members=inet4dst_address,valid
build_support=no
parse_support=yes

[inet4dst_address]
type=string
key="address"
is_child=yes
struct_name=vtermif_inet4dst
build_support=no
parse_support=no

[vtermif_dscp]
type=struct
key="vtn-set-inet-dscp-action"
is_child=yes
struct_name=vtermif_flow_action
members=dscp_value,valid
build_support=no
parse_support=yes

[dscp_value]
type=int
key="dscp"
is_child=yes
mandatory=yes
struct_name=vtermif_dscp
build_support=no
parse_support=yes

[vtermif_tpsrc]
type=struct
key="vtn-set-port-src-action"
is_child=yes
struct_name=vtermif_flow_action
members=port_value,valid
build_support=no
parse_support=no

[port_value]
type=int
key="port"
is_child=yes
struct_name=vtermif_tpsrc
build_support=no
parse_support=no

[vtermif_tpdst]
type=struct
key="vtn-set-port-dst-action"
is_child=yes
struct_name=vtermif_flow_action
members=tpdst_port,valid
build_support=no
parse_support=no

[tpdst_port]
type=int
key="port"
is_child=yes
struct_name=vtermif_tpdst
build_support=no
parse_support=no

[vtermif_icmptype]
type=struct
key="vtn-set-icmp-type-action"
is_child=yes
struct_name=vtermif_flow_action
members=icmp_type,valid
build_support=no
parse_support=no

[icmp_type]
type=int
key="type"
is_child=yes
struct_name=vtermif_icmptype
build_support=no
parse_support=no

[vtermif_icmpcode]
type=struct
key="vtn-set-icmp-code-action"
is_child=yes
struct_name=vtermif_flow_action
members=icmp_code,valid
build_support=no
parse_support=no

[icmp_code]
type=int
key="code"
is_child=yes
struct_name=vtermif_icmpcode
build_support=no
parse_support=no

[vtermif_flow_action]
type=array
key="vtn-flow-action"
is_child=yes
struct_name=vtermif_flow_action
members=order,vtermif_dlsrc,vtermif_vlanpcp,vtermif_dldst,vtermif_inet4src,vtermif_inet4dst,vtermif_dscp,vtermif_tpsrc,vtermif_tpdst,vtermif_icmptype,vtermif_icmpcode,valid
check_bool_set=no
build_support=no
parse_support=yes

[vtermif_flow_filter]
type=array
key="vtn-flow-filter"
is_child=yes
struct_name=vtermif_flow_filter
mandatory=yes
members=condition,index,vtermif_vtn_pass_filter,vtermif_vtn_drop_filter,vtermif_vtn_redirect_filter,vtermif_flow_action,valid
check_bool_set=yes
build_support=no
parse_support=yes

[vinterface_flow_filter]
type=struct
key="vinterface-input-filter"
is_child=no
check_bool_set=no
struct_name=vtermif_flow_filter
members=vtermif_flow_filter,valid
build_support=no
parse_support=yes

[pa_vterm_if_flowfilters]
type=struct
key="vinterface-flow-filter"
is_child=yes
check_bool_set=yes
struct_name=vinterface_flow_filter
members=vtermif_flow_filter
build_support=no
parse_support=no

[vtermif_filter]
type=array
key="vinterface"
is_child=no
check_bool_set=yes
struct_name=vtermif_flow_filter
members=vinterface_flow_filter
build_support=no
parse_support=yes

[vtermif_flowfilter_parser]
type = READ,CU,DEL
request_type = object
parse_request_members = vtermif_filter
build_request_members = pa_vterm_if_flowfilters
response_members = "ip_vterm_if_flowfilters"

[vtermif_flowfilter_request]
type = READ,CU,DEL
interface = tenantName,termName,ifName
request_type=object
request_members = pa_vterm_if_flowfilters
response_members = "ip_vterm_if_flowfilters"

[ROOT]
url_class = vtermif_flowfilter_request
parse_class = vtermif_flowfilter_parser
namespace = odcdriver
struct_type = vtermif_filter
data = vtermif_redirect_destination,vtermif_vtn_redirect_filter,vtermif_vtn_drop_filter,vtermif_vtn_pass_filter,vtermif_dlsrc,vtermif_vlanpcp,vtermif_dldst,vtermif_inet4src,vtermif_inet4dst,vtermif_dscp,vtermif_tpsrc,vtermif_tpdst,vtermif_icmptype,vtermif_icmpcode,vtermif_flow_action,vtermif_flow_filter,vinterface_flow_filter,vtermif_filter
methods = vtermif_flowfilter_request
