# Copyright (c) 2015 NEC Corporation
# All rights reserved.
#
# This program and the accompanying materials are made available under the
# terms of the Eclipse Public License v1.0 which accompanies this
# distribution, and is available at http://www.eclipse.org/legal/epl-v10.html

[SLASH]
type=url_string
value="/"

[COLON]
type=url_string
value=":"

[VTERM_GETSUPPORT_URL]
type=url_string
url_format=GET_BASEURL,SLASH,tenantName


[VTERM_COMANSUPPORT_URL]
type=url_string
url_format=BASEURL,SLASH,VTERMINALS,COLON,Vterminal-update

[VTERM_DELSUPPORT_URL]
type=url_string
url_format=BASEURL,SLASH,VTERMINALS,COLON,Vterminal-delete

[GET_BASEURL]
type=url_string
value="/restconf/operational/vtn:vtns/vtn"


[BASEURL]
type=url_string
value="/restconf/operations"

[tenantName]
type=url_string
get_abstract=yes

[VTERMINALS]
type=url_string
value="vtn-vterminal"

[Vterminal-update]
type=url_string
value="update-vterminal"

[Vterminal-delete]
type=url_string
value="remove-vterminal"


[vterm_parser]
type=READ,CU,DEL
request_type=object
parse_request_members=vtn_vterm_conf
build_request_members=ip_vterminals
response_members="vterminals"


[READ]
url=VTERM_GETSUPPORT_URL

[CU]
url=VTERM_COMANSUPPORT_URL

[DEL]
url=VTERM_DELSUPPORT_URL

[vterm_class]
type=READ,CU,DEL
interface=tenantName
request_type=object
request_members=vterminals
response_members="vterminals"

[vterminal_config]
type=struct
key="vterminal-config"
struct_name = vterminal_conf
members=vterm_description,valid
build_support=no
parse_support=yes

[vterm_description]
type=string
key="description"
struct_name=vterminal_config
build_support=no
parse_support=yes

[valid]
type=bool
key=""
struct_name= vterminal_conf
mandatory=no
build_support=no
parse_support=no

[vterminal_conf]
type=array
key="vterminal"
is_child=yes
check_bool_set=yes
struct_name = vterminal_conf
members=name,vterminal_config,valid
build_support=yes
parse_support=yes

[vtn_vterm_conf]
type=object
key="vtn"
is_child=yes
check_bool_set=yes
struct_name = vterminal_conf
members=vterminal_conf
build_support=no
parse_support=yes

[vterminals]
type=object
key="vterminals"
is_child=yes
check_bool_set=yes
struct_name = vterminal_conf
members=vterminal_conf
build_support=no
parse_support=no

[name]
type=string
key="name"
struct_name=vterminal_conf
build_support=no
parse_support=yes

[input_vterm]
type=struct
key="input"
is_child=yes
check_bool_set=yes
struct_name=ip_vterminal
members=update_mode,operation,tenant_name,vterminal_name,description,valid
mandatory=yes
build_support=yes
parse_support=yes

[update_mode]
type=string
key="update-mode"
struct_name=input_vterm
mandatory=yes
build_support=yes
parse_support=no

[operation]
type=string
key="operation"
struct_name=input_vterm
mandatory=yes
build_support=yes
parse_support=no

[tenant_name]
type=string
key="tenant-name"
struct_name=input_vterm
mandatory=yes
build_support=yes
parse_support=no

[vterminal_name]
type=string
key="terminal-name"
struct_name=input_vterm
mandatory=yes
build_support=yes
parse_support=no

[description]
type=string
key="description"
struct-name=input_vterm
mandatory=yes
build_support=yes
parse_support=no

[valid]
type=bool
key=""
struct_name= ip_vterminal
mandatory=no
build_support=no
parse_support=no


[ip_vterminal]
type=struct
key="ip_vterminal"
is_child=yes
check_bool_set=yes
struct_name=ip_vterminal
members=input_vterm,valid
build_support=yes
parse_support=no

[ip_vterminals]
type=object
key="ip_vterminals"
is_child=yes
check_bool_set=yes
struct_name=ip_vterminal
members=ip_vterminal
build_support=yes
parse_support=no


[ROOT]
url_class = vterm_class
parse_class=vterm_parser
namespace=odcdriver
struct_type = vtn_vterm_conf,input_vterm
data= vterminal_config,vterminal_conf,vtn_vterm_conf,input_vterm,ip_vterminal
methods= vterm_class
