# Copyright (c) 2015 NEC Corporation
# All rights reserved.
#
# This program and the accompanying materials are made available under the
# terms of the Eclipse Public License v1.0 which accompanies this
# distribution, and is available at http://www.eclipse.org/legal/epl-v10.html

[BASEURL]
type=url_string
value="/restconf/operations"

[GET_REST_URL]
type=url_string
value="/restconf/operational"

[SLASH]
type=url_string
value="/"

[VTN_PORT]
type=url_string
value="vtn-port-map"

[COLON]
type=url_string
value=":"

[SET_PORT]
type=url_string
value="set-port-map"

[DEL_PORT]
type=url_string
value="remove-port-map"

[VTN]
type=url_string
value="vtn:vtns/vtn"

[tenantname]
type=url_string
get_abstract=yes

[termname]
type=url_string
get_abstract=yes

[interfaces]
type=url_string
value = "vinterface"

[vterminals]
type=url_string
value="vterminal"

[ifname]
type=url_string
get_abstract=yes

[valid]
type=bool
key=""
mandatory=no
struct_name = vterm_if
build_support=no
parse_support=no

[VTERM_GETSUPPORT_URL]
type=url_string
url_format=GET_REST_URL,SLASH,VTN,SLASH,tenantname,SLASH,vterminals,SLASH,termname,SLASH,interfaces,SLASH,ifname

[VTERM_COMANSUPPORT_URL]
type=url_string
url_format=BASEURL,SLASH,VTN_PORT,COLON,SET_PORT

[VTERM_DELSUPPORT_URL]
type=url_string
url_format=BASEURL,SLASH,VTN_PORT,COLON,DEL_PORT

[vtermif_portmap]
type=READ,CU,DEL
request_type=object
parse_request_members=vterm_if
build_request_members=ip_vterminal_configs
request_members=vterminal_config
response_members="vterminal-config"

[vterm_if]
type=struct
key="port-map-config"
is_child=no
check_bool_set=yes
struct_name=vterm_if
members=vlan_id,node_id,port
build_support=no
parse_support=yes

[vlan_id]
type=int
key="vlan-id"
struct_name=vterm_if
is_child=yes
build_support=no
parse_support=yes

[node_id]
type=string
key="node"
struct_name=vterm_if
is_child=yes
check_bool_set=no
build_support=no
parse_support=yes

[port]
type=string
key="port-name"
struct_name=vterm_if
is_child=yes
check_bool_set=no
build_support=no
parse_support=yes

[valid]
type=bool
key=""
struct_name=vterm_if
mandatory=no
build_support=no
parse_support=no

[READ]
url=VTERM_GETSUPPORT_URL

[CU]
url=VTERM_COMANSUPPORT_URL

[DEL]
url=VTERM_DELSUPPORT_URL

[vtermifport_class]
type=READ,CU,DEL
interface=tenantName,termName,ifName
request_type=object
request_members=vterminal_config
response_members="vterminal_config"

[vterminal_config]
type=object
key="vterminal-config"
is_child=yes
check_bool_set=yes
struct_name = vterm_if
members=vterm_if
build_support=no
parse_support=no

[tenant_name]
type=string
key="tenant-name"
struct_name=input_vtermif_port
mandatory=yes
build_support=yes
parse_support=no

[terminal_name]
type=string
key="terminal-name"
struct_name=input_vtermif_port
mandatory=yes
build_support=yes
parse_support=no

[interface_name]
type=string
key="interface-name"
struct_name=input_vtermif_port
mandatory=yes
build_support=yes
parse_support=no

[node]
type=string
key="node"
struct_name=input_vtermif_port
mandatory=yes
build_support=yes
parse_support=no

[port_name]
type=string
key="port-name"
struct_name=input_vtermif_port
mandatory=yes
build_support=yes
parse_support=no

[vlan]
type=int
key="vlan"
struct_name=input_vtermif_port
is_child=yes
build_support=yes
parse_support=no
mandatory=no

[valid]
type=bool
key=""
struct_name=ip_vtermif_port
mandatory=no
build_support=no
parse_support=no

[input_vtermif_port]
type=struct
key="input"
is_child=yes
check_bool_set=yes
struct_name=vtermifport_input
members=tenant_name,terminal_name,interface_name,node,port_name,vlan,valid
build_support=yes
parse_support=no


[ip_vtermif_port]
type=struct
key="ip_vtermif_port"
is_child=yes
check_bool_set=yes
struct_name=ip_vtermif_port
members=input_vtermif_port,valid
build_support=yes
parse_support=no

[ip_vterminal_configs]
type=object
key="ip_vterminal_configs"
is_child=yes
check_bool_set=yes
struct_name=ip_vtermif_port
members=ip_vtermif_port
build_support=yes
parse_support=no

[ROOT]
url_class = vtermifport_class
parse_class=vtermif_portmap
namespace=odcdriver
struct_type = vterm_if,ip_vtermif_port
data=vterm_if,input_vtermif_port,ip_vtermif_port
methods= vtermifport_class
