# Copyright (c) 2015 NEC Corporation
# All rights reserved.
#
# This program and the accompanying materials are made available under the
# terms of the Eclipse Public License v1.0 which accompanies this
# distribution, and is available at http://www.eclipse.org/legal/epl-v10.html

[SLASH]
type=url_string
value="/"

[COLON]
type=url_string
value=":"

[VTN_GETSUPPORT_URL]
type=url_string
url_format=GET_BASEURL

[VTN_COMANSUPPORT_URL]
type=url_string
url_format=BASEURL,SLASH,VTNS,COLON,CU_VTN

[VTN_DELSUPPORT_URL]
type=url_string
url_format=BASEURL,SLASH,VTNS,COLON,DEL_VTN

[GET_BASEURL]
type=url_string
value="/restconf/operational/vtn:vtns"

[BASEURL]
type=url_string
value="/restconf/operations"


[CU_VTN]
type=url_string
value="update-vtn"

[GET_VTN]
type=url_string
value="vtns"

[DEL_VTN]
type=url_string
value="remove-vtn"

[VTNS]
type=url_string
value="vtn"

[vtn_parser]
type=READ,CU,DEL
request_type=object
parse_request_members=vtns
build_request_members=ip_vtns
response_members="vtns"


[READ]
url=VTN_GETSUPPORT_URL

[CU]
url=VTN_COMANSUPPORT_URL

[DEL]
url=VTN_DELSUPPORT_URL

[vtn_class]
type=READ,CU,DEL
request_type=object
request_members=vtns
response_members="vtns"

[description]
type=string
key="description"
struct_name=vtenant_config
build_support=no
parse_support=yes

[vtenant_config]
type=struct
key="vtenant-config"
struct_name=vtn_conf
members = description,valid
build_support=no
parse_support=yes


[update_mode]
type=string
key="update-mode"
struct_name=input
build_support=yes
mandatory=yes
parse_support=no

[operation]
type=string
key="operation"
struct_name= input
build_support=yes
mandatory=yes
parse_support=no

[ip_description]
type=string
key="description"
struct_name= input
build_support=yes
mandatory=yes
parse_support=no

[tenant_name]
type=string
key="tenant-name"
struct_name= input
build_support=yes
mandatory=yes
parse_support=no

[vtn_conf]
type=array
key="vtn"
is_child=yes
check_bool_set=no
struct_name = vtn_conf
members=vtn_name,vtenant_config,valid
build_support=no
parse_support=yes

[input]
type=struct
key="input"
is_child=yes
check_bool_set=no
struct_name = ip_vtn
members=tenant_name,update_mode,operation,ip_description,valid
build_support=yes
mandatory=yes
parse_support=no

[valid]
type=bool
key=""
struct_name=ip_vtn
mandatory=no
build_support=no
parse_support=no

[valid]
type=bool
key=""
struct_name=vtn_conf
mandatory=no
build_support=no
parse_support=no

[vtns]
type=object
key="vtns"
is_child=yes
check_bool_set=yes
struct_name = vtn_conf
members=vtn_conf

[ip_vtn]
type=struct
key="ip_vtn"
is_child=yes
check_bool_set=yes
struct_name = ip_vtn
members= input,valid
build_support=yes
parse_support=no

[ip_vtns]
type=array
key="ip_vtns"
is_child=yes
check_bool_set=yes
struct_name = ip_vtn
members= ip_vtn
build_support=yes
parse_support=no


[vtn_name]
type=string
key="name"
struct_name=vtn_conf
build_support=no
parse_support=yes

[ROOT]
url_class = vtn_class
parse_class=vtn_parser
namespace=odcdriver
struct_type = vtn_conf,ip_vtn
data= vtenant_config,vtn_conf,input,ip_vtn
methods= vtn_class
