# Copyright (c) 2016 NEC Corporation
# All rights reserved.
#
# This program and the accompanying materials are made available under the
# terms of the Eclipse Public License v1.0 which accompanies this
# distribution, and is available at http://www.eclipse.org/legal/epl-v10.html

[BASEURL]
type=url_string
value="/restconf/operations"

[GET_BASEURL]
type=url_string
value="/restconf/operational"

[SLASH]
type=url_string
value="/"

[VTN]
type=url_string
value="vtn:vtns/vtn"

[vtn_flw_filter]
type=url_string
value="vtn-flow-filter"

[set_flow_filter]
type=url_string
value="set-flow-filter"

[remove_flow_filter]
type=url_string
value="remove-flow-filter"

[vtn_input_filter]
type=url_string
value="vtn-input-filter"

[COLON]
type=url_string
value=":"

[tenantName]
type=url_string
get_abstract=yes

[VTNFLOWFILTER_ENTRY_GETSUPPORT_URL]
type=url_string
url_format=GET_BASEURL,SLASH,VTN,SLASH,tenantName

[VTNFLOWFILTER_ENTRY_COMANSUPPORT_URL]
type=url_string
url_format=BASEURL,SLASH,vtn_flw_filter,COLON,set_flow_filter

[VTNFLOWFILTER_ENTRY_DELSUPPORT_URL]
type=url_string
url_format=BASEURL,SLASH,vtn_flw_filter,COLON,remove_flow_filter

[READ]
url=VTNFLOWFILTER_ENTRY_GETSUPPORT_URL

[CU]
url=VTNFLOWFILTER_ENTRY_COMANSUPPORT_URL

[DEL]
url=VTNFLOWFILTER_ENTRY_DELSUPPORT_URL

[par_flow_action]
type=array
key="vtn-flow-action"
is_child=yes
struct_name=par_flow_action
members=order,par_vlanpcp,par_dscp,valid
check_bool_set=yes
mandatory=yes
build_support=no
parse_support=yes

[order]
type=int
key="order"
is_child=yes
struct_name=par_flow_action
mandatory=yes
build_support=no
parse_support=yes

[par_vlanpcp]
type=struct
key="vtn-set-vlan-pcp-action"
is_child=yes
struct_name=par_flow_action
members=vlan_pcp,valid
mandatory=no
build_support=no
parse_support=yes

[vlan_pcp]
type=int
key="vlan-pcp"
is_child=yes
mandatory=yes
struct_name=par_vlanpcp
build_support=no
parse_support=yes

[par_dscp]
type=struct
key="vtn-set-inet-dscp-action"
is_child=yes
struct_name=par_flow_action
members=dscp_value,valid
build_support=no
mandatory=no
parse_support=yes

[dscp_value]
type=int
key="dscp"
is_child=yes
struct_name=par_dscp
mandatory=yes
build_support=no
parse_support=yes

[valid]
type=bool
key=""
mandatory=no
struct_name=par_flow_action
build_support=no
parse_support=no

[par_vtn_drop_filter]
type=struct
key="vtn-drop-filter"
is_child=yes
struct_name=par_flow_filter
members=drop_empty,valid
mandatory=no
build_support=no
parse_support=yes

[drop_empty]
type=int
key=" "
is_child=yes
mandatory=no
struct_name=par_vtn_drop_filter
build_support=no
parse_support=yes

[par_vtn_pass_filter]
type=struct
key="vtn-pass-filter"
is_child=yes
struct_name=par_flow_filter
mandatory=no
members=pass_empty,valid
build_support=no
parse_support=yes

[pass_empty]
type=int
key=" "
is_child=yes
mandatory=no
struct_name=par_vtn_pass_filter
build_support=no
parse_support=yes

[index]
type=int
key="index"
is_child=yes
mandatory=yes
struct_name=par_flow_filter
build_support=no
parse_support=yes

[condition]
type=string
key="condition"
is_child=yes
mandatory=yes
struct_name=par_flow_filter
build_support=no
parse_support=yes

[par_flow_filter]
type=array
key="vtn-flow-filter"
is_child=yes
check_bool_set=yes
struct_name=par_flow_filter
mandatory=yes
members=condition,index,par_vtn_pass_filter,par_vtn_drop_filter,par_flow_action,valid
build_support=no
parse_support=yes

[par_vtn_flowfilter]
type=struct
key="vtn-input-filter"
is_child=no
check_bool_set=no
struct_name=par_flow_filter
members=par_flow_filter,valid
mandatory=no
build_support=no
parse_support=yes

[pa_vtn_flowfilters]
type=struct
key="vtenant-flow-filter"
is_child=yes
check_bool_set=yes
struct_name=par_vtn_flowfilter
members=par_flow_filter
mandatory=no
build_support=no
parse_support=no

[vtenant_filter]
type=array
key="vtn"
is_child=no
check_bool_set=yes
struct_name=par_flow_filter
members=par_vtn_flowfilter
build_support=no
mandatory=no
parse_support=yes

[vtnflowfilter_parser]
type=READ,CU,DEL
request_type=object
parse_request_members=vtenant_filter
build_request_members=pa_vtn_flowfilters
response_members="ip_vtn_flowfilters"

[vtnflowfilter_request]
type=READ,CU,DEL
interface=tenantName
request_type=object
request_members=pa_vtn_flowfilters
response_members="ip_vtn_flowfilters

[ROOT]
url_class=vtnflowfilter_request
parse_class=vtnflowfilter_parser
namespace=odcdriver
struct_type=vtenant_filter
data=par_vtn_drop_filter,par_vtn_pass_filter,par_vlanpcp,par_dscp,par_flow_action,par_flow_filter,par_vtn_flowfilter,vtenant_filter
methods=vtnflowfilter_request
