# Copyright (c) 2016 NEC Corporation
# All rights reserved.
#
# This program and the accompanying materials are made available under the
# terms of the Eclipse Public License v1.0 which accompanies this
# distribution, and is available at http://www.eclipse.org/legal/epl-v10.html

[BASEURL]
type=url_string
value="/restconf/operations"

[GET_BASEURL]
type=url_string
value="/restconf/operational"

[SLASH]
type=url_string
value="/"

[VTN]
type=url_string
value="vtn:vtns/vtn"

[tenantName]
type=url_string
get_abstract=yes

[vtn_flw_filter]
type=url_string
value="vtn-flow-filter"

[set_flow_filter]
type=url_string
value="set-flow-filter"

[remove_flow_filter]
type=url_string
value="remove-flow-filter"

[COLON]
type=url_string
value=":"

[VTNFLOWFILTER_ENTRY_GETSUPPORT_URL]
type=url_string
url_format=GET_BASEURL,SLASH,VTN,SLASH,tenantName

[VTNFLOWFILTER_ENTRY_COMANSUPPORT_URL]
type=url_string
url_format=BASEURL,SLASH,vtn_flw_filter,COLON,set_flow_filter

[VTNFLOWFILTER_ENTRY_DELSUPPORT_URL]
type=url_string
url_format=BASEURL,SLASH,vtn_flw_filter,COLON,remove_flow_filter

[READ]
url=VTNFLOWFILTER_ENTRY_GETSUPPORT_URL

[CU]
url=VTNFLOWFILTER_ENTRY_COMANSUPPORT_URL

[DEL]
url=VTNFLOWFILTER_ENTRY_DELSUPPORT_URL

[output]
type=bool
key="output"
is_child=yes
check_bool_set=yes
mandatory=yes
struct_name=input_vtn_flowfilter
build_support=yes
parse_support=no

[tenant_name]
type=string
key="tenant-name"
is_child=yes
check_bool_set=yes
mandatory=yes
struct_name=input_vtn_flowfilter
build_support=yes
parse_support=no

[vt_flow_filter]
type=array
key="vtn-flow-filter"
is_child=yes
check_bool_set=yes
struct_name=vt_flow_filter
mandatory=yes
members=condition,index,drop_filter,pass_filter,vt_flow_action,valid
build_support=yes
parse_support=no

[condition]
type=string
key="condition"
is_child=yes
mandatory=yes
struct_name=vt_flow_filter
build_support=yes
parse_support=no

[index]
type=int
key="index"
is_child=yes
mandatory=yes
struct_name=vt_flow_filter
build_support=yes
parse_support=no

[drop_filter]
type=struct
key="vtn-drop-filter"
is_child=yes
struct_name=vt_flow_filter
mandatory=no
members=drop_empty,valid
build_support=yes
parse_support=no

[drop_empty]
type=string
key=""
mandatory=no
struct_name=drop_filter
build_support=no
parse_support=no

[pass_filter]
type=struct
key="vtn-pass-filter"
is_child=yes
struct_name=vt_flow_filter
mandatory=no
members=pass_empty,valid
build_support=yes
parse_support=no

[pass_empty]
type=string
key=" "
mandatory=no
struct_name=pass_filter
build_support=no
parse_support=no

[vt_flow_action]
type=array
key="vtn-flow-action"
is_child=yes
check_bool_set=no
mandatory=yes
struct_name=vt_flow_action
members=order,vtn_vlanpcp,vtn_dscp,valid
build_support=yes
parse_support=no

[order]
type=int
key="order"
is_child=yes
mandatory=yes
struct_name=vt_flow_action
build_support=yes
parse_support=no

[vtn_vlanpcp]
type=struct
key="vtn-set-vlan-pcp-action"
is_child=yes
mandatory=no
sturct_name=vt_flow_action
members=vlan_pcp,valid
build_support=yes
parse_support=no

[vlan_pcp]
type=int
key="vlan-pcp"
is_child=yes
mandatory=yes
struct_name=vtn_vlanpcp
build_support=yes
parse_support=no

[vtn_dscp]
type=struct
key="vtn-set-inet-dscp-action"
is_child=yes
struct_name=vt_flow_action
members=dscp_value,valid
mandatory=no
build_support=yes
parse_support=no

[dscp_value]
type=int
key="dscp"
is_child=yes
struct_name=vtn_dscp
mandatory=no
build_support=yes
parse_support=no

[valid]
type=bool
key=""
mandatory=no
build_support=no
parse_support=no

[input_vtn_flowfilter]
type=struct
key="input"
is_child=yes
check_bool_set=yes
struct_name=ip_vtn_flowfilter
members=output,tenant_name,vt_flow_filter,valid
build_support=yes
mandatory=no
parse_support=no

[ip_vtn_flowfilter]
type=struct
key="ip_vtn_flowfilter"
is_child=yes
check_bool_set=yes
struct_name=ip_vtn_flowfilter
members=input_vtn_flowfilter,valid
build_support=yes
mandatory=no
parse_support=no

[ip_vtn_flowfilters]
type=object
key="ip_vtn_flowfilters"
is_child=yes
check_bool_set=yes
struct_name=ip_vtn_flowfilter
members=ip_vtn_flowfilter
mandatory=no
build_support=yes
parse_support=no

[vtn_flowfilters]
type=object
key="ip_vtn_flowfilters"
is_child=yes
check_bool_set=yes
struct_name=ip_vtn_flowfilter
members=vtn_flowfilters
build_support=no
mandatory=no
parse_support=no

[vtnflowfilter_entry_class]
type = READ,CU,DEL
request_type = object
interface = tenantName
request_members = ip_vtn_flowfilters
response_members = "ip_vbr_flowfilters"

[vtnflowfilter_entry_parser]
type = READ,CU,DEL
request_type = object
parse_request_members = vtn_flowfilters
build_request_members = ip_vtn_flowfilters
response_members = "ip_vbr_flowfilters"

[ROOT]
url_class=vtnflowfilter_entry_class
parse_class=vtnflowfilter_entry_parser
namespace=odcdriver
struct_type=vt_flow_filter, ip_vtn_flowfilter
data=vtn_vlanpcp,vtn_dscp,pass_filter,drop_filter,vt_flow_action,vt_flow_filter,input_vtn_flowfilter,ip_vtn_flowfilter
methods=vtnflowfilter_entry_class
