[vbridge_name]
type=string
key=name
ipc_struct=key_vbr_t
ipc_name=vbridge_name
category=mandatory
ipc_valid_flag=no
category=mandatory
get_support=yes
set_support=no
get_abstract=no
set_abstract=no

[vbridge_description]
type=string
key=description
ipc_struct=val_vbr_t
ipc_name=vbr_description
ipc_valid_flag=yes
category=mandatory
ipc_valid_enum=UPLL_IDX_DESC_VBR
get_support=yes
set_support=yes
get_abstract=no
set_abstract=no

[vbridge_ageinterval]
type=int
key=ageinterval
min=10
max=1000000
ipc_valid_flag=no
category=mandatory
get_support=no
set_support=no
get_abstract=no
set_abstract=yes

[vbridge_faults]
type=int
key=faults
count=0
ipc_valid_flag=no
category=mandatory
get_support=no
set_support=no
get_abstract=no
set_abstract=yes

[vbridge_state]
type=int
key=state
min=-1
max=1
ipc_valid_flag=no
category=mandatory
get_support=no
set_support=no
get_abstract=no
set_abstract=yes

[vbridge]
type=object
members=vbridge_name,vbridge_description,vbridge_ageinterval,vbridge_faults,vbridge_state
get_support=yes
set_support=yes

[vbridges]
key=vbridge
type=object
item=vbr
set_support=yes
get_support=yes


[code]
namespace=odcdriver

[class]
name=VbrParser
set_method=create_vbr_request
set_sections=vbridge
get_method=parse_vbr_response
get_sections=vbridges
rest_type=json_object
ipc_key_struct=key_vbr_t
ipc_val_struct=val_vbr_t

