[vterminal_name]
type=string
key=name
ipc_struct=key_vterm_t
ipc_name=vterminal_name
category=mandatory
ipc_valid_flag=no
category=mandatory
get_support=yes
set_support=no
get_abstract=no
set_abstract=no

[vterminal_description]
type=string
key=description
ipc_struct=val_vterm_t
ipc_name=vterm_description
ipc_valid_flag=yes
category=mandatory
ipc_valid_enum=UPLL_IDX_DESC_VBR
get_support=yes
set_support=yes
get_abstract=no
set_abstract=no

[vterminal_faults]
type=int
key=faults
count=0
ipc_valid_flag=no
category=mandatory
get_support=no
set_support=no
get_abstract=no
set_abstract=yes

[vterminal_state]
type=int
key=state
min=-1
max=1
ipc_valid_flag=no
category=mandatory
get_support=no
set_support=no
get_abstract=no
set_abstract=yes

[vterminal]
type=object
members=vterminal_name,vterminal_description,vterminal_faults,vterminal_state
get_support=yes
set_support=yes

[vterminals]
key=vterminal
type=object
item=vterm
set_support=yes
get_support=yes

[code]
namespace=odcdriver

[class]
name=VtermParser
set_method=create_vterm_request
set_sections=vterminal
get_method=parse_vterm_response
get_sections=vterminals
rest_type=json_object
ipc_key_struct=key_vterm_t
ipc_val_struct=val_vterm_t
