/*
 * Copyright (c) 2013 NEC Corporation
 * All rights reserved.
 *
 * This program and the accompanying materials are made available under the
 * terms of the Eclipse Public License v1.0 which accompanies this
 * distribution, and is available at http://www.eclipse.org/legal/epl-v10.html
 */

package org.opendaylight.vtn.manager.internal.cluster;

import org.slf4j.Logger;

import org.opendaylight.vtn.manager.internal.VTNManagerImpl;

/**
 * {@code FlowModResultEvent} describes an cluster event object which reports
 * result of flow modification.
 *
 * <p>
 *   Although this class is public to other packages, this class does not
 *   provide any API. Applications other than VTN Manager must not use this
 *   class.
 * </p>
 */
public class FlowModResultEvent extends ClusterEvent {
    private static final long serialVersionUID = 1772757786660826935L;

    /**
     * The name of flow entry.
     */
    private final String  flowName;

    /**
     * Result of flow modification.
     */
    private final FlowModResult  flowModResult;

    /**
     * Construct a new flow mod result event.
     *
     * @param name    The name of flow entry.
     * @param result  The result of flow modification.
     */
    public FlowModResultEvent(String name, FlowModResult result) {
        flowName = name;
        flowModResult = result;
    }

    /**
     * Invoked when a cluster event has been received.
     *
     * @param mgr    VTN Manager service.
     * @param local  {@code true} if this event is generated by the local node.
     */
    @Override
    protected void eventReceived(VTNManagerImpl mgr, boolean local) {
        if (!local) {
            mgr.setRemoteFlowResult(flowName, flowModResult);
        }
    }

    /**
     * Record a trace log which indicates that a cluster event has been
     * received from remote node.
     *
     * @param mgr     VTN Manager service.
     * @param logger  A logger instance.
     * @param key     A cluster event key associated with this event.
     */
    @Override
    public void traceLog(VTNManagerImpl mgr, Logger logger,
                         ClusterEventId key) {
        logger.trace("{}: {}: Received flow mod result: name={}, result={}",
                     mgr.getContainerName(), key, flowName, flowModResult);
    }

    /**
     * Determine whether this event should be delivered on the VTN task thread
     * or not.
     *
     * @param local  {@code true} if this event is generated by the local node.
     *               {@code false} if this event is generated by remote cluster
     *               node.
     * @return  {@code true} is returned if this event should be delivered
     *          on the VTN task thread. Otherwise {@code false} is returned.
     */
    @Override
    public boolean isSingleThreaded(boolean local) {
        return false;
    }
}
