/*
 * Copyright (c) 2013, 2015 NEC Corporation.  All rights reserved.
 *
 * This program and the accompanying materials are made available under the
 * terms of the Eclipse Public License v1.0 which accompanies this distribution,
 * and is available at http://www.eclipse.org/legal/epl-v10.html
 */

package org.opendaylight.vtn.manager.internal.cluster;

import org.opendaylight.vtn.manager.VBridge;
import org.opendaylight.vtn.manager.VBridgePath;
import org.opendaylight.vtn.manager.internal.VTNManagerImpl;

import org.opendaylight.controller.sal.core.UpdateType;

/**
 * {@code VBridgeEvent} describes an cluster event object which notifies that
 * a virtual bridge was added, modified, or removed.
 *
 * <p>
 *   Although this class is public to other packages, this class does not
 *   provide any API. Applications other than VTN Manager must not use this
 *   class.
 * </p>
 */
public final class VBridgeEvent extends VNodeEvent {
    /**
     * Version number for serialization.
     */
    private static final long serialVersionUID = 9091399353628568529L;

    /**
     * Generate a virtual bridge event which indicates that the bridge has
     * been added.
     *
     * @param mgr      VTN Manager service.
     * @param path     Path to the virtual bridge.
     * @param vbridge  Information about the virtual bridge.
     */
    public static void added(VTNManagerImpl mgr, VBridgePath path,
                             VBridge vbridge) {
        mgr.enqueueEvent(new VBridgeEvent(path, vbridge, UpdateType.ADDED,
                                          true));
    }

    /**
     * Generate a virtual bridge event which indicates that the bridge has
     * been changed.
     *
     * @param mgr      VTN Manager service.
     * @param path     Path to the virtual bridge.
     * @param vbridge  Information about the virtual bridge.
     * @param save     {@code true} means that the tenant configuration should
     *                 be saved.
     */
    public static void changed(VTNManagerImpl mgr, VBridgePath path,
                               VBridge vbridge, boolean save) {
        mgr.enqueueEvent(new VBridgeEvent(path, vbridge, UpdateType.CHANGED,
                                          save));
    }

    /**
     * Generate a virtual bridge event which indicates that the bridge has
     * been removed.
     *
     * @param mgr      VTN Manager service.
     * @param path     Path to the virtual bridge.
     * @param vbridge  Information about the virtual bridge.
     * @param save     {@code true} means that the tenant configuration should
     *                 be saved.
     */
    public static void removed(VTNManagerImpl mgr, VBridgePath path,
                               VBridge vbridge, boolean save) {
        mgr.enqueueEvent(new VBridgeEvent(path, vbridge, UpdateType.REMOVED,
                                          save));
    }

    /**
     * Construct a new virtual bridge event.
     *
     * @param path     Path to the virtual bridge.
     * @param vbridge  Information about the virtual bridge.
     * @param type     Update type.
     * @param save     {@code true} means that the tenant configuration should
     *                 be saved.
     */
    private VBridgeEvent(VBridgePath path, VBridge vbridge, UpdateType type,
                         boolean save) {
        super(path, vbridge, type, save);
    }

    /**
     * Return information about the virtual bridge.
     *
     * @return  Information about the virtual bridge.
     */
    public VBridge getVBridge() {
        return (VBridge)getObject();
    }

    /**
     * Invoked when a cluster event has been received.
     *
     * @param mgr    VTN Manager service.
     * @param local  {@code true} if this event is generated by the local node.
     */
    @Override
    protected void eventReceived(VTNManagerImpl mgr, boolean local) {
        super.eventReceived(mgr, local);

        if (!local) {
            UpdateType type = getUpdateType();
            if (type == UpdateType.REMOVED) {
                // Destroy MAC address table.
                VBridgePath path = (VBridgePath)getPath();
                mgr.removeMacAddressTable(path, isSaveConfig());
            }
        }
    }

    /**
     * Return the name of node type.
     *
     * @return  A string which describes the type of this virtual node.
     */
    @Override
    public String getTypeName() {
        return "virtual bridge";
    }

    /**
     * Deliver this event to {@code IVTNManagerAware} listeners.
     *
     * @param mgr  VTN Manager service.
     */
    @Override
    public void notifyEvent(VTNManagerImpl mgr) {
        VBridgePath path = (VBridgePath)getPath();
        VBridge vbridge = getVBridge();
        UpdateType type = getUpdateType();
        mgr.notifyListeners(path, vbridge, type);
    }
}
