/*
 * Copyright (c) 2014 NEC Corporation
 * All rights reserved.
 *
 * This program and the accompanying materials are made available under the
 * terms of the Eclipse Public License v1.0 which accompanies this
 * distribution, and is available at http://www.eclipse.org/legal/epl-v10.html
 */

package org.opendaylight.vtn.manager.internal.cluster;

import org.slf4j.Logger;

import org.opendaylight.vtn.manager.internal.VTNManagerImpl;

import org.opendaylight.controller.sal.core.UpdateType;

/**
 * {@code VTenantPathMapEvent} describes an cluster event object which
 * notifies that a VTN path map was added, changed, or removed.
 *
 * <p>
 *   Although this class is public to other packages, this class does not
 *   provide any API. Applications other than VTN Manager must not use this
 *   class.
 * </p>
 */
public final class VTenantPathMapEvent extends ClusterEvent {
    /**
     * Version number for serialization.
     */
    private static final long serialVersionUID = 1581191956276087307L;

    /**
     * The name of the virtual tenant.
     */
    private final String tenantName;

    /**
     * The index number of the VTN path map.
     */
    private final int  index;

    /**
     * Update type of this event.
     */
    private final UpdateType  updateType;

    /**
     * Generate a VTN path map event which indicates that the VTN path map was
     * added, removed, or changed.
     *
     * @param mgr    VTN Manager service.
     * @param tname  The name of the virtual tenant.
     * @param idx    The index of the VTN path map.
     * @param type   Update type.
     */
    public static void raise(VTNManagerImpl mgr, String tname, int idx,
                             UpdateType type) {
        mgr.enqueueEvent(new VTenantPathMapEvent(tname, idx, type));
    }

    /**
     * Construct a new VTN path map event.
     *
     * @param tname  The name of the virtual tenant.
     * @param idx    The index of the VTN path map.
     * @param type   Update type.
     */
    private VTenantPathMapEvent(String tname, int idx, UpdateType type) {
        tenantName = tname;
        index = idx;
        updateType = type;
    }

    /**
     * Return the name of the virtual tenant.
     *
     * @return  The name of the virtual tenant.
     */
    public String getTenantName() {
        return tenantName;
    }

    /**
     * Return the index of the container path map.
     *
     * @return  The index of the container path map.
     */
    public int getIndex() {
        return index;
    }

    /**
     * Return update type of this event.
     *
     * @return  Update type.
     */
    public UpdateType getUpdateType() {
        return updateType;
    }

    /**
     * Invoked when a cluster event has been received.
     *
     * @param mgr    VTN Manager service.
     * @param local  {@code true} if this event is generated by the local node.
     */
    @Override
    protected void eventReceived(VTNManagerImpl mgr, boolean local) {
        if (!local) {
            mgr.updateVTenantPathMap(tenantName, index, updateType);
        }
    }

    /**
     * Record a trace log which indicates that a cluster event has been
     * received from remote node.
     *
     * @param mgr     VTN Manager service.
     * @param logger  A logger instance.
     * @param key     A cluster event key associated with this event.
     */
    @Override
    public void traceLog(VTNManagerImpl mgr, Logger logger,
                         ClusterEventId key) {
        logger.trace("{}:{}: Received VTN path map event: " +
                     "tenant={}, index={}, type={}",
                     mgr.getContainerName(), key, tenantName, index,
                     updateType);
    }

    /**
     * Determine whether this event should be delivered on the VTN task thread
     * or not.
     *
     * @param local  {@code true} if this event is generated by the local node.
     *               {@code false} if this event is generated by remote cluster
     *               node.
     * @return  {@code true} is returned if this event should be delivered
     *          on the VTN task thread. Otherwise {@code false} is returned.
     */
    @Override
    public boolean isSingleThreaded(boolean local) {
        return true;
    }
}
