/*
 * Copyright (c) 2012-2014 NEC Corporation
 * All rights reserved.
 * 
 * This program and the accompanying materials are made available under the
 * terms of the Eclipse Public License v1.0 which accompanies this
 * distribution, and is available at http://www.eclipse.org/legal/epl-v10.html
 */

package org.opendaylight.vtn.javaapi.ipc.enums;

public class UncUPLLEnums {

	public static final String UPLL_IPC_CHANNEL_NAME = "lgcnwd"; /*
															 * UPLL IPC
															 * Channel Name
															 */
	public static final String UPLL_IPC_SERVICE_NAME = "upll"; /*
															 * UPLL IPC
															 * Service Name
															 */

	/* UPLL IPC Service Ids */
	public enum ServiceID {
		UPLL_EDIT_SVC_ID, /* Key Tree edit services */
		UPLL_READ_SVC_ID, /* Key Tree read services */
		UPLL_CONTROL_SVC_ID, /* Key Tree control services */
		UPLL_GLOBAL_CONFIG_SVC_ID; /* UPLL GlobalConfig services */
	}

	/* UPLL IPC Operations supported under GlobalConfig Service ID */
	public enum UpllGlobalConfigOpT {
		UPLL_IS_CANDIDATE_DIRTY_OP(101),
		UPLL_IMPORT_CTRLR_CONFIG_OP(102),
		UPLL_MERGE_IMPORT_CONFIG_OP(103),
		UPLL_CLEAR_IMPORT_CONFIG_OP(104),
		UPLL_IS_KEY_TYPE_IN_USE_OP(105);

		private final int value;

		private UpllGlobalConfigOpT(final int value) {
			this.value = value;
		}

		public int getValue() {
			return value;
		}
	}

	/* Event Types generated by UPLL */
	public enum EventType {
		UPLL_EV_CONFIG_NOTIFICATION, UPLL_EV_OPER_NOTIFICATION;
	}
}
